### ISSUE TITLE
[UI]: Export table tsv

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#10]
**Goal:** Make the `export table` button work.

Discussed in meeting on Oct 12 with Rosi and Ann - this is probably not necessary anymore. We can revisit other ways to communicate metrics with DACO in the future

## Expected Behaviour

- [x] Clicking the button should download a tsv of the table columns
- [ ] The tsv data should reflect the current sort order of the table (if the administrator sorts by application #, for instance)
- [ ] The tsv data should reflect the filtered table (If the administrator searches the table to view only certain rows of the table, for instance)

![image](https://user-images.githubusercontent.com/18424138/117190220-25cbe900-adad-11eb-82dd-4a3c647d13a0.png)

**Comment by kcullion** [comment]
As @rosibaj discussed in sprint planning. We may wait do implement this button until after MVP

**Comment by rosibaj** [comment]
@kcullion moving to ice-boc/on-hold for now

**Comment by rosibaj** [comment]
note:  this still needs backend.

**Comment by b-f-chan** [comment]
TSV is downloadable, but if sorted or filtered, that part is not implemented

**Comment by b-f-chan** [comment]
You can sort in Excel, closing
