### ISSUE TITLE
Feature Request: Partial Outage Notifications 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#102]
- when Collaboratory is down, S3 storage will not be available, but the rest of the application will be available. 
- Disable just document upload/download when collab is down with a notification method on the parts of the application that require it.
-

**Comment by b-f-chan** [comment]
We have implemented a manual maintenance mode for Collab outages, so this may not be strictly required anymore

**Comment by b-f-chan** [comment]
Closing
