### ISSUE TITLE
[UI + data hookup] 404/401/Maintenance/Error pages

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#103]
## Goal
Build the following pages and hook them up for the correct events. 
Note: these are the same designs from ARGO - so hopefully code can be reused. 

**Zeplin links:**
404: https://zpl.io/aRRplm0
403: https://zpl.io/2E40Xml
Maintenance Page: https://zpl.io/aNOQlEv
Error Page: https://zpl.io/amLZG8K

## Expected Behaviour
- [x] Show the 404 page when a page doesn't exist 
Links: **Documentation** to: https://docs.icgc-argo.org/docs/data-access/daco/applying
**Home** to the DACO homepage
- [x] Show the 403 page when the user is not authorized to view a page. (links same as above)
- [ ] Show the maintenance page during maintenance periods when collab is down. Also - hide the top right buttons for "Apply for Access" and "Login"
- [x] Show the error page when a server error or other error occurs.

**Comment by kcullion** [comment]
@ciaranschutte 

- [ ] i went to a gibberish url and thought I would see the 404 page but I see this. Is that hooked up?

![image](https://user-images.githubusercontent.com/18424138/129078888-f012624a-61be-4484-a170-8de7c3a9766d.png)

- [ ] when I choose an application number that isn't mind I see the above too. But in this case wouldn't I see a 403?

- [ ] But when I log out and go to a gibberish url I see the 404 page but with a double header and double footer

![image](https://user-images.githubusercontent.com/18424138/129079183-8a709dfd-991d-473a-add2-cf3ef020a489.png)

- [ ] Is there a way I can test the maintenance and error pages?

**Comment by ciaranschutte** [comment]
something odd with the logged in user route error status. i will look into it.

**Comment by kcullion** [comment]
thanks @ciaranschutte moved this back to in progress

**Comment by kcullion** [comment]
@ciaranschutte I saw the error page when recreating this bug https://github.com/icgc-argo/dac-ui/issues/289

But it also has the double header and footer
![image](https://user-images.githubusercontent.com/18424138/129264393-3d0126ea-7669-41d3-8ffa-646c7744de48.png)

**Comment by ciaranschutte** [comment]
thinking about this a little more:
- I think navigating to wrong "page" should be generic error. Only let frontend know what's necessary.
- 403 makes sense because a user might have to ask admin for access I think? Or something internal doesn't have correct access maybe? 

So I'm going to do generic error for all except 403

**Comment by rosibaj** [comment]
@ciaranschutte this sounds ok to me

**Comment by ciaranschutte** [comment]
covers https://github.com/icgc-argo/platform-ui/issues/1937
