### ISSUE TITLE
[UI]: Application state progress bars

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#12]
**Goal:** To set up the application progress bar component in storybook.
There's a similar component for ARGO to utilize: https://argo-ui-storybook.netlify.app/?path=/story/uikit-progress--progress-bar

These will be added to the dashboard card and the application page titlebar.

# Expected Outcome
Have the following progress bars set up for the following application states
- [ ] Draft: https://zpl.io/a8ngJGJ
![image](https://user-images.githubusercontent.com/18424138/117209968-16f13080-adc5-11eb-9cc5-ebf75161e915.png)
- [ ] Submit & Sign: https://zpl.io/29mQEYy
![image](https://user-images.githubusercontent.com/18424138/117210059-338d6880-adc5-11eb-8264-971af38668d7.png)
- [ ] DACO Review: https://zpl.io/bo3qGrZ
![image](https://user-images.githubusercontent.com/18424138/117210148-4c961980-adc5-11eb-93b0-b14f95c22053.png)
- [ ] Approved: https://zpl.io/2ZMEE7J
![image](https://user-images.githubusercontent.com/18424138/117210213-620b4380-adc5-11eb-9923-f0b4286b1915.png)
- [ ] Revisions Needed: https://zpl.io/Vx3zv5R
![image](https://user-images.githubusercontent.com/18424138/117210274-751e1380-adc5-11eb-8762-a08f6f637888.png)
- [ ] Rejected: https://zpl.io/VKdRLY6
![image](https://user-images.githubusercontent.com/18424138/117210330-8535f300-adc5-11eb-8b7f-477b28847c62.png)
- [ ] Closed (before approving): https://zpl.io/bJDmm8D
![image](https://user-images.githubusercontent.com/18424138/117210718-0f7e5700-adc6-11eb-947b-b0ac44864485.png)
- [ ] Closed (after approving): https://zpl.io/2j366Kx
![image](https://user-images.githubusercontent.com/18424138/117211015-7b60bf80-adc6-11eb-908d-1d203bb51543.png)

**Comment by rosibaj** [comment]
@kcullion i am going to move this ticket forward. if ui feedback is needed we can incorporate that once data has been connected and we can see the states. 

Thank you @ciaranschutte !

**Comment by daniel-cy-lu** [comment]
I didn't edit anything. I clicked and un-clicked one of the check-boxes by accident when I was studying the history on this epic.

**Comment by caravinci** [comment]
Though the state for those checkboxes is persisted in github, it doesn't change the tickets' statuses on the board in any meaningful way.

We (devs) use them to keep track of task completion, but BAs generally only care for the ticket being tagged as ready to test, regardless of the checkboxes.
