### ISSUE TITLE
PDF: Static text between app + pdf

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#127]
- dont want to duplicate text between the ui pages and pdf creating a copy-paste nightmare
- I’m working on a setup to have all the static text shared between the ui and the pdf

**Comment by anncatton** [comment]
Initial setup in `0.9.0`:
- hookup pdf download to `Draft PDF` button (button does not reflect app state yet)
- pdf will show static text for `Introduction` and `Applicant Information`
- `Introduction` acknowledgement should show correct state from what is latest in the api
- watermark should reflect current app state
- `Applicant Information` has only static text and form data subtitle, no app state yet

Work for the rest of the pdf is continuing and will appear in a later release
