### ISSUE TITLE
Publication Validation 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#138]
The publication urls must be unique in a publication, and there must be at least 3 provided urls. 

The API has been updated to handle this: 
-  When duplicate URLs are submitted, the API will save them with an error (example below):
```
        "projectInfo": {
            "publicationsURLs": [
                "https://thisisaurl.com",
                "https://thisisaurl.com",
                ""
            ],
            "background": "This is a project description.  This is a project description. This is a project description. ",
            "methodology": "This is a project description. This is a project description. ",
            "aims": "This is a project description. This is a project description. ",
            "website": "",
            "title": "This is a project title.",
            "summary": "This is a project description. This is a project description. ",
            "meta": {
                "errorsList": [
                    {
                        "field": "publications",
                        "message": "Publication URLS must be unique"
                    }
                ],
                "status": "INCOMPLETE"
            }
        },
```

## Expected behaviour
- When this error is observed, the UI should 
  - highlight in red BOTH urls that are duplicate with the error `Publication URLs must be unique.` 
  - the error should persist until the user changes the URL 
  - The error should show if the user reloads the page

- [ ] currently if the user puts in the same URL as one they already have,  allow them to put in that same url but show the following error message:
Error message in zeplin: https://zpl.io/V0ooDew
![image](https://user-images.githubusercontent.com/18424138/128063027-1a115a8f-8c30-44cd-93ba-0fc6b1ab8eb8.png)

**Comment by samrichca** [comment]
bug ciaran found: validation doesn't account for empty fields

**Comment by kcullion** [comment]
Thanks @samrichca this looks good in QA. Just logged the bug that @rosibaj found here for the next sprint: https://github.com/icgc-argo/dac-ui/issues/439

**Comment by rosibaj** [comment]
@samrichca can i get a version on this ticket please?

**Comment by samrichca** [comment]
@rosibaj done!
