### ISSUE TITLE
[UI]: Application page with basic titlebar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#14]
**Goal:** To set up the basic structure of the application page
Zeplin: https://zpl.io/2y3AnAy

## Expected Outcomes
To have the following elements on the page
- [x] 1. Page titlebar with application details
- My Applications (links back to the dashboard page)
- Application Number/ID
- Two dates (for now Create on and Last updated date)
- A spot to feed in the Applicant name and institution name (when not filled out in the form this will say "to be specified")
- [ ] 2. Progress bar from: https://github.com/icgc-argo/dac-ui/issues/12
- [x] 3. Various global action buttons (`close application` and `download pdf` for now)
- [x] 4. The card that holds the application with the general application title 
- [x] 5. Set up previous/next buttons for the sections

(table of contents will be built in this ticket https://github.com/icgc-argo/dac-ui/issues/15) 

![image](https://user-images.githubusercontent.com/18424138/117358296-fa67fd80-ae83-11eb-957f-ab3ac9074aef.png)

**Comment by rosibaj** [comment]
Testing URL: https://dac.qa.argo.cancercollaboratory.org/applications/DACO-1 
notes: 
- better tabs coming in #15, so no comments on this here
- drop shadow is missing - this will also be fixed in #15. 
![image](https://user-images.githubusercontent.com/15824252/118881670-53db1e00-b8c1-11eb-9d80-97c4c0d6e75b.png)

This is a great start thank you @caravinci!

**Comment by rosibaj** [comment]
Note: No 2 moved to new ticket: #38

**Comment by kcullion** [comment]
@caravinci @anncatton I just noticed the favicon isn't working on this link. Ann I feel like you had a fix for that?

**Comment by rosibaj** [comment]
@caravinci did you get all of the header updates correctly  from develop? i see the favicon correctly here: https://dac.qa.argo.cancercollaboratory.org/

**Comment by kcullion** [comment]
@caravinci this is really nitpicky of me heheh...but when that content area gets taller, can you make the top and bottom margins the same?
![image](https://user-images.githubusercontent.com/18424138/118989412-035ed180-b950-11eb-8c40-5e3c6c4cfd6e.png)

**Comment by rosibaj** [comment]
@caravinci can you please include the above content with #15?

**Comment by caravinci** [comment]
Not at all, @kcullion. Keep the feedback coming!
That spacing is sure something I am now addressing in #15.
