### ISSUE TITLE
Ethics Section V2 - PRE APPROVAL STATE 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#141]
- the ethics section was done quickly and hardwired to NO selection for ease of testing 
- this ticket is to complete the implementation of the ethics section, before the application is in an APPROVED State. 
- implementation of POST approved stat is covered here:  https://github.com/icgc-argo/dac-ui/issues/58

**Zeplin links:**
Applicant chooses option 1: https://zpl.io/29mmLkB
Applicant chooses option 2, with empty table: https://zpl.io/VYqqeye
Error state when not uploading a file: https://zpl.io/ad33gDE
Uploaded files table: https://zpl.io/bPEEe5m

## Expected Outcomes

- [x] 1) When the section is first loaded, an empty radio button state is shown. 
- [x] 2) if option one is selected, it is saved and the user receives a green checkmark on the left status tab. 
- [x] 3) When the applicant selects the 2nd option, a new form element appears with empty file table and an upload button: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/609c153c3edb22adcfe24cd9
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/ea00b823-808e-40c0-9e08-0c3aa3efe378)
- [x] 4) When a file is uploaded it gets displayed in a table with the date updated date: https://zpl.io/bPEEe5m
  - UI: 
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/59f7dfd1-5cdd-4e0b-9977-9f0fd9bd349d)
  - Endpoint for button to work: https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/post_applications__id__assets__type__upload (select type ETHICS)
- [x] 5) If a file has been uploaded, the action of delete can be executed on ANY file in the list. When the icons is clicked, the file is removed.  as long as there is one file, the status icon in the left bar should be green.  
  - Endpoint for delete icon: https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/delete_applications__id__assets__type__assetId__assetId_ 
 - [x] 6) If the applicant doesn't upload a file and the save is compelted, or deleted all uploaded files, then they see this empty table area and button red and error message.  at this point there would be a red icon in the status bar. 
 https://zpl.io/ad33gDE
 - [x] 7) Validations for file upload: Has to be a pdf, doc, docx.  Should be limited in the file upload box!

**Comment by caravinci** [comment]
This ticket should also trim whitespace around text fields when persisted.

**Comment by kcullion** [comment]
@caravinci looking good...some feedback:

- [ ] The user should be able to delete the ethics letter when in "SIGN AND SUBMIT" state. Currently clicking on the trashcan does nothing

**Comment by rosibaj** [comment]
Follow-up issues: 
can only select false on 2nd click https://github.com/icgc-argo/dac-ui/issues/248
