### ISSUE TITLE
[UI + Data Hookup] Error banners in modals

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#142]
## Goal
To hookup the possible error states into the modals. 

## Expected Outcomes
When an error occurs from a modal action:
- [x] 1. Show the correct error banner
- [x] 2. Keep the entered data in the fields
- [x] 3. Keep the action buttons enabled for them to try again 
For example: 
![image](https://user-images.githubusercontent.com/18424138/122598774-48535200-d03b-11eb-8e3a-fb1bcb36d4c5.png)

## Possible errors for Add a Collaborator modal
- [x] Applicant is trying to add the same collaborator twice (BE ticket: https://github.com/icgc-argo/dac-api/issues/35)
Zeplin: https://zpl.io/bzdm8dE
![image](https://user-images.githubusercontent.com/18424138/122598332-b0edff00-d03a-11eb-8f1f-10e28802ddf2.png)

- [x] Applicant is trying to add themselves as a collaborator (BE ticket: https://github.com/icgc-argo/dac-api/issues/35)
Zeplin: https://zpl.io/blO5lne
![image](https://user-images.githubusercontent.com/18424138/122598367-bcd9c100-d03a-11eb-950e-fa6b87d7b36b.png)

- [x] Something went wrong and they need to try again. Zeplin: https://zpl.io/29GWqMB
![image](https://user-images.githubusercontent.com/18424138/122598729-383b7280-d03b-11eb-8456-0162525fa9e7.png)

## Possible errors for Request Revisions modal and the Approve modal (from DACO Admin)
- [ ] Something went wrong and they need to try again. https://zpl.io/29GWqMB
![image](https://user-images.githubusercontent.com/18424138/122598723-35d91880-d03b-11eb-9d1f-fc9b59e86968.png)

**Comment by samrichca** [comment]
not an official scope change but a suggestion: approval modal should have the same error as the request revisions modal

**Comment by kcullion** [comment]
@samrichca good point! yes we can make a note to add the "something went wrong" banner to the approved modal

**Comment by kcullion** [comment]
@ciaranschutte looks good!

- when adding the PI emails into the collaborator form, I see the banner, the values are saved and when I fix I am able to submit the form
- when adding the same collaborator twice (at least one of the same emails), I see the banner, the values are saved and when I fix I am able to submit the form
- I just can't really test the "Something went wrong" banners.

Can you just fix:
- [ ] remove the "x" on the banners - they are not dismissible, and it's not working right now
![image](https://user-images.githubusercontent.com/18424138/128389405-932a7b63-c336-4b4e-a862-3329a6ffb456.png)

**Comment by kcullion** [comment]
@ciaranschutte I'm going to move that one small feedback to a new ticket so we can at lease release this to staging

**Comment by ciaranschutte** [comment]
@kcullion sounds good thank you

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
