### ISSUE TITLE
Verify sorting on admin table columns 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#147]
- api is being changed
- ui should work but needs to be verified when api is ready. 
- [x] can only sort one time on the table.  second sort does not work on some fields.
- [x] set default number of rows to 50

**Comment by samrichca** [comment]
change page size from 5 to 20

5 was for UI testing

**Comment by kcullion** [comment]
@samrichca @rosibaj this has been verified to be working...
The only think left is to show 50 applications by default (we think 50 is better than 20)

**Comment by rosibaj** [comment]
verified on QA - i see 50 rows by default now.  thank you @samrichca
