### ISSUE TITLE
[Data Hookup]: Make Sections Auto-Save on edit 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#161]
Follow-up to #49

## Goal
For each application section, the applicant can edit data and it is auto-saved with the correct functionality as outlined in the wiki `Application Form Save Functionality` table: https://wiki.oicr.on.ca/display/icgcargotech/DACO+Technical+Specifications

## Endpoint to use
- this relies on the PATCH Applications/id 

## Expected Outcomes
All behaviors outlined on the wiki are working, which include:
- [x] User fills out values in fields and they are automatically saved when leaving the field

Note: saving and editing for collaborators is broken out into this ticket; https://github.com/icgc-argo/dac-ui/issues/52
And ethics in this ticket; https://github.com/icgc-argo/dac-ui/issues/58

**Comment by kcullion** [comment]
@caravinci just as a note so we test with this ticket:
- [ ] in DACO-70 I added a value for Researcher Profile URL in section A and Project website in section d and they didn't come through on the UI.

**Comment by caravinci** [comment]
For documentation purposes: We found an issue with the word counter, and will fix it with #163

https://github.com/icgc-argo/dac-ui/issues/163#issuecomment-874983809
> As part of this ticket, I'll also ensure the word counter tracks the number upon loading data from BE.
> ![image.png](https://camo.githubusercontent.com/f1cbcbee9717bf79e68e57a9957a53b7dd4510e6ff9148d79c957d39846cf421/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564656663653366393962636630623162386139386432342f34613931316133612d313131652d346534362d623839312d643636383636663362616431)

**Comment by kcullion** [comment]
mentioned to @caravinci ...just a copy change for the note in section B. this should be
`Must be the institutional email address of the Institutional Representative.`
![image](https://user-images.githubusercontent.com/18424138/124819433-3f6ae780-df3a-11eb-8f3e-a71b7649475d.png)

**Comment by caravinci** [comment]
Worth mentioning:
- The `Publication URLs` add/remove behaviour is iffy, and will be revised at #138. Use at your own risk ☠️ 
- Noticed the API doesn't validate whether there's duplicate URLs (at least it seemed this way when I used the same valid url in the 4th and 5th fields.) May be worth double checking whether that logic is present or needs improvement.

**Comment by rosibaj** [comment]
Re point three:
> - If the Representative's Primary Affiliation is filled before the Applicant's (i.e. if the Applicant's Affiliation hasn't been set yet), then Representative is currently being validated as complete, which shouldn't be the case since the two should match.

This is the correct behaviour - The validation on them not being the same should not kick in until the Applicants Primary Affiliation is taken into account. Once that is filled in, all affiliations will be validated to match against the Primary Affiliation of the applicant.

**Comment by caravinci** [comment]
Got it. thanks for clarifying! @rosibaj

**Comment by kcullion** [comment]
tested this ticket and I think we can move it. We are just opening save feedback bug tickets as we find them

**Comment by rosibaj** [comment]
Agree - preliminary data hookup is done here and a lot of sections can be saved. 

Follow-up bugs:
#188
#189 
#190 
#191

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/dac-api/issues/83
