### ISSUE TITLE
[ContentUpdate] General links and content

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#164]
## Header and Footer
- [x] `Policies and Guidelines` open in a new window: https://www.icgc-argo.org/page/72/introduction-and-goals-
- [x] `Help Guides` open in a new window: https://docs.icgc-argo.org/docs/data-access/daco/applying
- [x] `Controlled Data Users` open in a new window: https://www.icgc-argo.org/page/139/controlled-data-users 

## Homepage
- [x] `ICGC Policies and Guidelines`open in a new window: https://www.icgc-argo.org/page/72/introduction-and-goals-
- [x]  and `Data Access and Use Policies` - open in a new window: https://www.icgc-argo.org/page/132/data-access-and-data-use-policies-and-guidelines
![image](https://user-images.githubusercontent.com/18424138/126391506-d93ba7f8-3e2e-4ada-8ac4-8a0867a2ebd3.png)

- [x] Remove "with no undue risks to donors."
![image](https://user-images.githubusercontent.com/18424138/128031947-3f8b6511-f12d-455b-9577-c7d0a2f2e8a3.png)

## Applicant Dashboard
- [x] `eligible project teams` opens in a new window: https://docs.icgc-argo.org/docs/data-access/daco/applying#eligible-project-guidelines
![image](https://user-images.githubusercontent.com/18424138/126369553-cdd77d36-5c7c-41cf-b099-2cca2ec6a8ef.png)
- [x] change this to two year
![image](https://user-images.githubusercontent.com/18424138/126497933-5d2c6459-1160-4e15-a4b1-e9f7c99f99d4.png)

## Application Links

- [x] Section D - needs the lay summary page link, open in a new window: https://www.icgc-argo.org/page/139/controlled-data-users
![image](https://user-images.githubusercontent.com/18424138/128028436-88360102-c583-49ff-a51b-493c0e00266b.png)

**Comment by kcullion** [comment]
Looks great, thanks @caravinci !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
