### ISSUE TITLE
[UI]: Application Section A: Applicant Information Form & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#17]
**Goal:** To build Section A: Applicant Info section with working local validation.

**Zeplin links:**
Form: https://zpl.io/bz3mDAX
Form with errors: https://zpl.io/254W3G3

You can see a lot of these form elements and validation happening on this ARGO form: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/create

## Expected Outcomes
- [x] 1. Instructions
- [x] 2. Set up form using components in ARGO component library. 
- [x] 3. The form has two sections separated by headings.
- [x] 4. Some form elements have blue notes beside them
- [x] 5. Some form elements have placeholder text to show examples of what to fill out in the field (see this mockup for those: https://zpl.io/bz3mDAX)

**Local Validation** 
- [x] 6. All fields marked with * are required. If the user doesn't fill out and moves on to a new section they will see this error
- [x] 7. On top of required, the email fields need to be in a valid email format
- [x] 8. The website url has to be a valid url.

![image](https://user-images.githubusercontent.com/18424138/117362601-71ec5b80-ae89-11eb-916f-67827715c7f4.png)

**Comment by caravinci** [comment]
**This ticket required the following scope extensions (from the one initially established):**

To enable local validation

- Enable passing custom `blur` and `focus` handlers into the UiKit `Input` (as well as an obvious focus shadow style, alike the one in the `Button` and `FormCheckbox` components), allowing to visually discern pristine vs touched vs valid/invalid statuses, etc.
- Similar additional functionality for the `Select` component, to ensure consistency.

**Comment by caravinci** [comment]
For VIII. Website, is it required or not? the Zeplin shows it as a Schrödinger:
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/e82820f7-b50f-48e9-8d46-e626a4418e24)
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/4a150bd7-974b-431e-82f1-d981644e9f42)

**Comment by kcullion** [comment]
@caravinci ooops I see that I put the required for website in one mock but not the other. This is required on the current application, so I think it's meant to be required

**Comment by caravinci** [comment]
Figured that was the case and worked under that assumption, but it's good to double check :) thank you, @kcullion!

**Comment by caravinci** [comment]
This ticket relies on some changes made to the Select and Multiselect components.
The change was necessary because a user without a mouse would break the validation and didn't want that edge case to block testing + approval. 

Known issue: Wasn't able to cover all edge cases for the Multi select, though I did fix a few basic ones.
Will for sure have to continue working on it later. Moving on to other more urgent tasks.

**Comment by kcullion** [comment]
thanks @caravinci . Small request for field label and note change.

Please change "Institution/Company Website" label to `Researcher Profile URL`
And the blue note will be `Please provide a link to your profile on your institution/company website.`
This field is still not required.
Zeplin mockup: https://zpl.io/bz3mDAX

**Comment by caravinci** [comment]
Excellent timing. Changes will be in by the time this gets to QA.
@blabadi I'm leaving the field name the same, unless you want to change it

**Comment by kcullion** [comment]
@caravinci they want to make "Researcher Profile URL" required. sorry for the last minute change

**Comment by caravinci** [comment]
no problem at all! I'll add that requirement to the PR.

**Comment by rosibaj** [comment]
- [ ] Google email vaidaiton is wrong; should just validation regular email format.
- [ ] Postal code validation is wrong; should not include comma 
- [ ] There is a build issue with styles; This should be resolved so the styling is translated correctly on build.

**Comment by caravinci** [comment]
Fixes for `Google email` and `city, provice/state` validation: https://github.com/icgc-argo/dac-ui/pull/88

**Comment by kcullion** [comment]
@caravinci some more feedback:
(FYI, just made this ticket to be worked on when there's time: https://github.com/icgc-argo/dac-ui/issues/93)

- [ ] For country - I shouldn't be able to add a new value in, I should have to select from the options that are listed. Like I was able to do this:
![image](https://user-images.githubusercontent.com/18424138/120553742-dcc87e00-c3c6-11eb-9b15-92e9ba8c7978.png)

- [ ] also when I got that error in the screenshot above, then went to the next field to fill it out - the error didn't persist for country like it did for the other required fields
- [ ] For country, when I do select a value from the list of options, I can still type after that option
![image](https://user-images.githubusercontent.com/18424138/120554272-8740a100-c3c7-11eb-9d2a-0eddced45cd4.png)

- [ ] The styles look different for that country value and the others - different font sizes and no left padding. The field itself looks taller than the others as well
![image](https://user-images.githubusercontent.com/18424138/120553978-2a44eb00-c3c7-11eb-9769-032dd5a0037a.png)

I will review again when the build issue with styles is fixed on QA

**Comment by caravinci** [comment]
Yeah! I was hoping someone would notice those issues too... that's current default behaviour at the Multiselect component, and I think you can see it in `platform-ui` at prod. 

I'd absolutely loooove to fix that, but didn't with this PR trying to keep the scope tight.
Looking forward to https://github.com/icgc-argo/dac-ui/issues/93!!

**Comment by kcullion** [comment]
@caravinci @rosibaj I moved the feedback about the country field to this ticket: https://github.com/icgc-argo/dac-ui/issues/93
