### ISSUE TITLE
UI Component Library: Fix disabled state font contrast

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#179]
When an application is locked for editing, the fields use the ARGO UI library disabled state. 
The font contrast is very low, so it's difficult to read the text, which could be important say to DACO admin or applicant who wants to review what they had said.

See zeplin: https://zpl.io/aBvEw80
Let's keep the filled in font colour the same (black).
and just grey out the field background.

**Comment by samrichca** [comment]
known issues: can't change the color of the title field because it uses a `color` attribute (uikit bug). has been logged in the wiki.

![image](https://user-images.githubusercontent.com/3540896/134060416-8fde6fa7-731e-4665-8e24-72a8c44c65a5.png)

**Comment by samrichca** [comment]
current QA testing scope: uikit/platform only. try storybook since we don't often disable fields in platform UI

**Comment by kcullion** [comment]
this looks great to me @samrichca ! nice work

**Comment by kcullion** [comment]
this is working in staging
