### ISSUE TITLE
[UI]: Application Section B: Institutional Representative Form & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#18]
**Goal:** To build Section B: Institutional Representative section with working local validation.

**Zeplin links:**
Form: https://zpl.io/VYqO9yM
Form with errors: I didn't mock this one up but please use same errors from https://github.com/icgc-argo/dac-ui/issues/17

You can see a lot of these form elements and validation happening on this ARGO form: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/create

## Expected Outcomes
- [x] 1. Instructions
- [x] 2. Set up form using components in ARGO component library. 
- [x] 3. The form has two sections separated by headings
- [x] 4. Some form elements have blue notes beside them
- [x] 5. Some form elements have placeholder text to show examples of what to fill out in the field (see this mockup for those: https://zpl.io/bz3mDAX)

**Local Validation** 
- [x] 6. All fields marked with * are required. If the user doesn't fill out and moves on to a new section they will see this error
- [x] 7. On top of required, the email field needs to be in a valid email format

**Note:**  the functionality for the "address same as applicant" will come later when application can be saved

![image](https://user-images.githubusercontent.com/18424138/117365121-d957da80-ae8c-11eb-9022-1d621cbbf32f.png)

**Comment by rosibaj** [comment]
Testd Jun 02, 12:06. Windows/Chrome. 
- [ ] checkbox not working. 
![image](https://user-images.githubusercontent.com/15824252/120514188-04a1ec80-c39b-11eb-99ae-a39ddcc52aac.png)

**Comment by caravinci** [comment]
I haven't added any logic to the checkbox (which means no functional `clickability`) as per the ticket comment:
> Note: the functionality for the "address same as applicant" will come later when application can be saved

Adding any clickability would've been throwaway code at this point, but I'm of course able to add that if desired/requested.

**Comment by rosibaj** [comment]
@caravinci ok makes sense! i wasn't sure as the introduction clicked!

**Comment by kcullion** [comment]
FYI - I outline that address checkbox functionality in this ticket for later: https://github.com/icgc-argo/dac-ui/issues/54

**Comment by rosibaj** [comment]
Feedback has been left in #17, so will close this one as the scope is completed.
