### ISSUE TITLE
[UI]: Application Section C: Collaborator Empty State + Table + actions

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#19]
**Goal:** To build Section C: Collaborators: empty table+full table views.

**Zeplin links:**
Empty View: https://zpl.io/bARRyKP
With Collaborators: https://zpl.io/a7PP8DM

## Expected Outcomes
- [x] 1. Instructions
- [x] 2. Empty Table
- [x] 3. "Add Collaborator" button

With collaborators. T**his is very similar to ARGO Program > Manage Program > Users section table**. Please refer to this for implementation.
- [x] 4. Collaborators table with correct column fields
- [x] 5. Display count of collaborators above the table
- [x] 6. Default sort order on "Collaborator Type" with "Authorized Personnel at the top (so can be alpha order)
- [x] 7. Actions: edit collaborator (which will open the modal in https://github.com/icgc-argo/dac-ui/issues/20 with the form fields filled out).
- [x] 8. Actions: delete collaborator - which, when clicked, will eventually have a confirmation modal similar to the "Remove User" modal in the ARGO section mentioned above).

![image](https://user-images.githubusercontent.com/18424138/118003655-c4f56100-b316-11eb-9e3c-325a18a36eed.png)
![image](https://user-images.githubusercontent.com/18424138/118004102-2cabac00-b317-11eb-84b2-aa0fa6890ed2.png)

**Comment by rosibaj** [comment]
lgtm!  @kcullion let me know if you have any feedback on this one!

**Comment by kcullion** [comment]
@ciaranschutte looks good and we will test the empty state when the application is all working!
