### ISSUE TITLE
Missing section borders in DAA of application form

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#196]
A grey border is no longer showing, due to some css inheritance issues on some of Static elements introduced for pdf:

- on DATA ACCESS AGREEMENTS:
![image](https://user-images.githubusercontent.com/18424138/126661251-72cfd776-4be4-4ea0-84f0-3a191ca52ebc.png)

**Comment by kcullion** [comment]
I now see the borders in the DAA section. Thanks @samrichca 
![image](https://user-images.githubusercontent.com/18424138/127348924-6388bed3-0079-4dca-8680-ea514e809180.png)
