### ISSUE TITLE
UI: Header and Footer

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#2]
- [ ] Logged out: https://zpl.io/aMoJPZR

## Logged out header
Most of the links will need to wait until when the content is on icgc-argo.org and docs.icgc-argo.org
![image](https://user-images.githubusercontent.com/18424138/117058683-edfd6c80-acec-11eb-97a4-77ae27918b79.png)
1. Links to homepage
2. TBD - Will link to a page on https://www.icgc-argo.org (open a new window)
3. TBD - Will link to a page on https://www.docs.icgc-argo.org (open a new window)
4. TBD - will link to a page on https://www.icgc-argo.org ((open a new window))
5. Will open a modal (another ticket to come)
6. Will link to login with google

## Footer
![image](https://user-images.githubusercontent.com/18424138/117058960-46cd0500-aced-11eb-9495-2a2b8f8b3b9b.png)
1. Links to https://www.icgc-argo.org (open a new window)
2. Links to https://www.platform.icgc-argo.org/contact  (open a new window)
3. TBD - Will link to a page on icgc-argo.org (open a new window)
4. TBD - Will link to a page on docs.icgc-argo.org (open a new window)
5. TBD - will link to a page on icgc-argo.org ((open a new window))
6. Links to https://www.icgc-argo.org (open a new window)
7. Links to https://www.platform.icgc-argo.org/  (open a new window)
8. Link to https://www.icgc-argo.org/page/2/privacy (open in a new window)
9. Link to https://www.icgc-argo.org/page/1/terms-and-conditions (open in a new window)
10. Link to https://www.icgc-argo.org/page/77/e3-publication-policy (open in a new window)
11. Link to https://www.gla.ac.uk/ (open in a new window)
12. Link to https://www.oicr.on.ca/ (open in a new window)

**Comment by anncatton** [comment]
@kcullion I forgot to add the Google icon to the login button, I'm adding it in #3

**Comment by anncatton** [comment]
Links that are TBD at the moment will link to their root url, i.e. `Policies and Guidelines` will go to `https://www.icgc-argo.org/`

**Comment by rosibaj** [comment]
@anncatton this looks great for now! Any feedback will be in future tickets! thank you!
