### ISSUE TITLE
[UI]: Application Section C: Add a Collaborator Modal & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#20]
**Goal:** To build Section C: Add/Edit a collaborator modal with working local validation.

**Zeplin links:**
Blank Modal: https://zpl.io/VDggJG3
Form with errors: https://zpl.io/V4NNpZ4
Valid form:  https://zpl.io/bARRJwp

**Note:** Justin has made a lot of these fields and validations work in section A and B, please reuse what you can.

## Expected Outcomes
- [x] 1. Set up modal with Instructions 
- [x] 2. Set up form using components in ARGO component library. 
- [x] 3. Some form elements have blue notes beside them
- [x] 4. Some form elements have placeholder text to show examples of what to fill out in the field 
~- [ ] 5. If the applicant chooses `Authorized Personnel` then show `Position Title` field as the last field. If the applicant chooses `Authorized Student` then show `Pursuing Degree` field as the last field. This defaults to showing `Position Title` field.~ Note: moved to follow-up ticket
~- [ ] 6. Button is disabled until the applicant fills in the form correctly~ Note: moved to follow-up ticket

**Local Validation**  See errors in https://zpl.io/V4NNpZ4
- [x] 7. All fields marked with * are required. 
~- [ ] 8. On top of required, the email field needs to be in a valid email format~ Note: moved to follow-up ticket
**Note:**  the functionality for the "Primary Affiliation must be the same as the Applicant" will come later when application can be saved https://github.com/icgc-argo/dac-ui/issues/54

**Correctly filled out form**: https://zpl.io/bARRJwp
~- [ ] 9. Once the form has valid entries, the "Add Collaborator" button is enabled.~ Note: moved to follow-up ticket

![image](https://user-images.githubusercontent.com/18424138/122599146-de877800-d03b-11eb-97fb-18d37cb162ab.png)

![image](https://user-images.githubusercontent.com/18424138/122599350-3a520100-d03c-11eb-95a4-dd937389dfc7.png)

![image](https://user-images.githubusercontent.com/18424138/122599393-4d64d100-d03c-11eb-9caf-3de67e00384a.png)

**Comment by ciaranschutte** [comment]
@rosibaj static UI is up in dev. QA momentarily. Had a chat with @caravinci and we'll need to break the validation of this into a separate ticket as it doesn't quite fit in with how we're currently processing

**Comment by rosibaj** [comment]
@ciaranschutte will do, breakign out ticket now.

**Comment by kcullion** [comment]
@ciaranschutte just some preliminary UI feedback in case you want to fix before moving. 
see zeplin for correct blue notes: https://zpl.io/VDggJG3
And Position Title should be required

![image](https://user-images.githubusercontent.com/18424138/124003219-ade10000-d9a4-11eb-8853-c4c2ef3745ed.png)

**Comment by rosibaj** [comment]
@ciaranschutte @caravinci  Remaining work abstracted to https://github.com/icgc-argo/dac-ui/issues/174

**Comment by rosibaj** [comment]
@kcullion i will move  your comment to #174
