### ISSUE TITLE
🐛 Ethics section unexpected error on refresh

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#203]
## Describe the bug
I'm getting the following errors when I refresh the ethics section on DACO-83 (QA)
 
![image](https://user-images.githubusercontent.com/18424138/125130750-80e0cb80-e0cf-11eb-9a40-df35844fb0ea.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Filled out false in postman for ethics required (This also happened when I submitted True and uploaded a file)
![image](https://user-images.githubusercontent.com/18424138/125130818-a79f0200-e0cf-11eb-8fff-3c2def2719b6.png)

2. Submitted that, and went to UI and refreshed section. I get this white screen
![image](https://user-images.githubusercontent.com/18424138/125130750-80e0cb80-e0cf-11eb-9a40-df35844fb0ea.png)

3. I can load a different application section but when I go to ethics section and refresh I get that error

## Expected behaviour
I should be able to refresh the ethics section without getting an error

**Comment by rosibaj** [comment]
tested Jul 13, 3:50
- added false via postman for ethics letter to https://dac.qa.argo.cancercollaboratory.org/applications/DACO-26?section=ethicsLetter
- loaded page and refreshed several times. no crash occurred.
