### ISSUE TITLE
🐛 Unclear behaviour in type ahead dopdown

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#208]
Here is a video of my bug:
- https://drive.google.com/file/d/1FC2pHKQEFIltwl_bmRBi7cV_Hcxooqs7/view- You can see in option 1, i can change the value as much as i want.  I do see this is a multiselect, and you can pick more than one.  Its more clear bc the existing ones are in pills, as opposed to text, however i can also just remove all the values.  It is a required field, so i can't save without it, but if it wasn't required i would be able to save. 
- This looks how i expect from storybook. 
- You can see once i get to the daco site, when i click in the dropdown it keeps my value that is selected, then i have to type beside that value.  If i want to clear this field bc i selected the wrong thing, i can't.  I think we should be able to clear this field. 
- Here is a link showing a better experience when inputting just one value: https://drive.google.com/file/d/14S5tn_22g1t3LMKwypilzv0CGGJj6-A-/view

**Comment by kcullion** [comment]
Closing this, combined with https://github.com/icgc-argo/dac-ui/issues/93
