### ISSUE TITLE
[UI]: Application Section D: Project Information Form & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#21]
**Goal:** To build Section D: Project Info section with working local validation.

**Zeplin links:**
Blank form: https://zpl.io/br3q8Z1
Form with errors1: https://zpl.io/V0ooDew
Form with errors2: https://zpl.io/aR448MK
Completed form with an extra publication: https://zpl.io/br336o5

You can see a lot of these form elements and validation happening on this ARGO form: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/create

## Expected Outcomes
- [x] 1. Instructions
- [x] 2. Set up form using components in ARGO component library. 
- [x] 3. The scientific abstract section has extensive instructions and text area components
- [x] 4. The publications have 3 items by default (cannot be deleted). 
- [x] 5. Once the applicant correctly fills out all three fields, the "Add another" button will enable and they can add another publication field.
- [x] 6. The publications fields added after the 3rd one can be deleted.
Note: this "add another" component can be seen on ARGO if you go to a specify program (as an administrator), click `Manage Program` in the sidebar, then click `Add users`. The add users modal accepts more than one user at a time.
- [x] 7. The project lay summary section has extensive instructions and a text area component. The link in the instructions is TBD. **(NOTE: the lay summary was added back in on May 27, and for time sake is only shown in this mockup, but behaves like the other text areas: https://zpl.io/br3q8Z1)**
- [x] emotional codependence: Fix the styling bug that was found with Section A (labels on top of form fields and responsive bugginess) 

**Local Validation** 
In this mockup: https://zpl.io/V0ooDew you will see
- [x] All fields marked with * are required. 
- [x] The website url has to be a valid url.
- [x] The abstract text areas have a max word count of 200. The word count updates and displays as applicant enters content in the field. Once the applicant hits 200 words, they should not be able to type further.
- [x] The lay summary text area has a max word count of 200 and behaves as above.
- [ ] The publication urls must be unique
- [ ]  There must be at least 3 publications provided

And seen in this mockup: https://zpl.io/aR448MK
- [x] The publications must be valid urls. 

![image](https://user-images.githubusercontent.com/18424138/117999956-6084d280-b313-11eb-8148-3099240c593d.png)

![image](https://user-images.githubusercontent.com/18424138/118000082-7db9a100-b313-11eb-8702-2dd6993f4cd0.png)

![image](https://user-images.githubusercontent.com/18424138/119869197-f1e86d00-beed-11eb-9bc1-f0176e0373d4.png)

**Comment by kcullion** [comment]
looks good @caravinci ...some feedback:

- [ ] font size change for blue instructions 
![image](https://user-images.githubusercontent.com/18424138/122575594-ea187600-d01e-11eb-9659-f2ca4edf4b07.png)

- [ ] for the add another publication, move the trashcan icon so it's vertically centered with the field and make top and bottom padding inside the box equal
![image](https://user-images.githubusercontent.com/18424138/122576306-8c385e00-d01f-11eb-943f-0247f21c6701.png)

**Comment by kcullion** [comment]
@caravinci as discussed on slack...

- [ ] change all url error messages to
`Please enter a valid url. Must begin with http:// or https://, for example, https://www.icgc-argo.org.`

**Comment by rosibaj** [comment]
Publication validation moved to: https://github.com/icgc-argo/dac-ui/issues/138

@caravinci i am going to move this back to in-progress now for these small changes!

**Comment by kcullion** [comment]
@caravinci a couple more things..

- [ ] The project website field should not be required. 
- [ ] Add validations to make sure publication urls are unique and use this error message, if not.
![image](https://user-images.githubusercontent.com/18424138/122583512-51d2bf00-d027-11eb-9c5f-c1bd0c80fc87.png)

**Comment by caravinci** [comment]
Noted, will submit changes asap.

For documentation purposes: We decided to leave the `Relevant Publications` validation + interaction pending, as it relies on connecting to the API for some of it (to avoid async issues that held back UI implementation).

**Comment by caravinci** [comment]
Does this look as desired?
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/7f604f80-e445-420d-83cc-55d0be93d0f1)

**Comment by kcullion** [comment]
@caravinci just putting this here so I don't forget, and it seems silly to make a ticket for it. For the Section B Primary Affiliation note, please change this to 
`Must match the applicant’s primary affiliation exactly. `
![image](https://user-images.githubusercontent.com/18424138/122593658-fce97580-d033-11eb-9fef-21501244384d.png)

Note the validation error will happen later on this ticket: https://github.com/icgc-argo/dac-ui/issues/54

**Comment by rosibaj** [comment]
lgtm! Thanks for the edits @caravinci !

**Comment by kcullion** [comment]
looks good to me too!
