### ISSUE TITLE
🐛 Investigate workarounds for autofill issue (Original title: Turn off autofill for fields on daco-ui)

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#211]
## Describe the bug
- Cannot add IR Address correctly, /other issues relating to autofill. 
- https://stackoverflow.com/questions/11708092/detecting-browser-autofill

 
## Steps To Reproduce
1. start a new application 
2. agree to the terms. 
3. skip applicant and fill in the IR fields.  Validations are incorrefctlt reported. 
Video: https://drive.google.com/file/d/1xOIOjiYK52Lrk-LDXBGhZaI2nZDOY8i0/view 
System: Windows 10/Chrome 
## Expected behaviour
We need to fix the buggy behaviour with autofill. If we can't turn autofill off, then the autofilled fields should at least be saved in the form.

**Comment by samrichca** [comment]
parking this for now

- disabling autocomplete is tricky & browser companies actively look for and close loopholes
- I decided instead to make the country multiselect work with autocomplete correctly
- I wasn't able to find any other implementation of uikit multiselect that has `single=true allowNew=false`
- I'm sure we could update uikit and our validation scripts but not today

**Comment by rosibaj** [comment]
- two issues: 
  - multi-select 
  - event-listening for the auto-fill

**Comment by akachru-github** [comment]
We cannot turn off auto-fill. 
Renaming this ticket to an investigation of potential workarounds for this problem.

**Comment by rosibaj** [comment]
tested Spet 20 - forms on platform look fine to me @samrichca !

**Comment by kcullion** [comment]
Tested with @samrichca on dev. This looks good to me :)

**Comment by kcullion** [comment]
autofill working as expected in staging
