### ISSUE TITLE
🐛 Add collaborator modal feedback: bugs 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#214]
## Testing from Jul 22, 2021: 

- [x] When the user adds a collaborator, the button should be labeled `Add Collaborator`
- [x] When editing a collaborator, the button should be labeled `Save Collaborator`
- [x] When "student" is selected, the placeholder for "pursuing degree" should read `e.g. Doctoral`
![image](https://user-images.githubusercontent.com/18424138/126696730-2a9e56f5-7946-4ef4-819b-3c419ec09ffa.png)

- [x] the title isn't saving again - when I put "Mrs." then save, then go back and edit the collaborator, it has cleared the title 
![image](https://user-images.githubusercontent.com/18424138/126697618-b13a8025-b215-4fc4-9703-5a6cc3421551.png)

## Testing from Jul 13, 2021: 

- [x] When the user adds a collaborator, `Add collaborator` button should be disabled by default and if there is a local validation error
![image](https://user-images.githubusercontent.com/15824252/125518695-cd3bf1e7-b6b8-4803-bfbf-a75755098393.png)

- [x] - when you close the modal, the values should also be cleared. https://drive.google.com/file/d/1O_GrCHbBjT0c4XWYvXf-qZW_oDxaIDXo/view 
This work was completed by Justin and tested on https://github.com/icgc-argo/dac-ui/issues/52

**Comment by caravinci** [comment]
The modal clearing is handled with #52.
Partial handling of the validation disabling the "add/edit" button also done, but not quite fully implemented yet. (pending handling validation + error response from API)

**Comment by caravinci** [comment]
The `title` field worked well for me in dev without any changes, after creating a new application.
I've left it unchecked for that reason, but we can bounce this ticket back to `in progress` if the problem persists.

**Comment by kcullion** [comment]
Thanks @caravinci just some feedback and I'll put this back into in progress.

- [ ] by default, this save collaborator button should be disabled. It only enables once the form is filled out correctly
![image](https://user-images.githubusercontent.com/18424138/127363766-59ab94e9-464d-4aaa-af56-2e4de05e9c4a.png)

- [ ] the title still clears for me in QA when I go back to edit. I had said "Dr." here
![image](https://user-images.githubusercontent.com/18424138/127364280-35605e83-2308-4629-91ed-0a0268cc08fc.png)

**Comment by caravinci** [comment]
Seems I had already "handled" the title issue in other sections, but the fix didn't get carried over when creating the layout for this modal. The `Select` component, used for the title, is not being tracked the first time it changes, but works well afterwards...

Dev Note: if we happen to add another `Select` in the future, don't forget to pass `onFocus={validateFieldTouched}` to ensure the "pristine/touched" logic tracks the change.

**Comment by rosibaj** [comment]
lgtm thank you @caravinci !
