### ISSUE TITLE
Data Hookup: Applicant Dashboard Cards 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#215]
![image](https://user-images.githubusercontent.com/15824252/125833826-b1f8c864-657a-49e8-bec5-09c6daabe6c4.png)
 

- **Endpoint:** https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/get_applications_ 
- As a user when i log-in: 
  - there is a card for each application that I have created. 
  - those cards display the data of each application 
  - Application states have specific card displays (listed below).  Based on the state an application is in, the card should display the correct configuration for that application 
 

## For testing 
- [x] 6.`Approved` card has an Expiry date on the top right. Zeplin: https://zpl.io/2ZMEE7J
- [x] `Draft` and Sign & Submit cards have an "Edit Application" button that links to the created application. 
Zeplin: https://zpl.io/a8ngJGJ
https://zpl.io/29mQEYy
- [x] `DACO Review` status has a "View Application" button that links to the locked application
Zeplin: https://zpl.io/bo3qGrZ
- [x] `Approved` card has two buttons: "View Application" and "Manage Collaborators"
- [x] `Revisions needed` card has an "Edit Application" button: Zeplin: https://zpl.io/Vx3zv5R

** NOTE Closed/Rejected are not in scope of this dont worry abou those yet

**Comment by kcullion** [comment]
Looks good...just some feedback:

- [ ] Can we consistently use the shortform for month (Jan. Feb. Mar. Apr. etc) - because the date has to fit in small areas sometimes
![image](https://user-images.githubusercontent.com/18424138/126500862-8a13fab8-c317-42ec-a557-04ed5de2984c.png)

**Comment by kcullion** [comment]
@samrichca I assume this isn't in QA yet?

**Comment by samrichca** [comment]
@kcullion correct!

**Comment by kcullion** [comment]
tested on QA and I now see all dates in the same format. thanks @samrichca 
![image](https://user-images.githubusercontent.com/18424138/126659935-f5c94ef5-30d9-44d1-bb6d-5f0e937cbdfa.png)
