### ISSUE TITLE
[Data Hookup] Dashboard card for Rejected applications

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#219]
## Rejected Card

Zeplin: https://zpl.io/VKdRLY6
- [ ]  UI and data hookup for the rejected state progress bar
- [x] the status sentence with the date of rejection
- [x] the "View Application" button  (links to the locked rejected application)
![image](https://user-images.githubusercontent.com/18424138/131025537-bcfca689-aa2a-44bc-9f5e-6939f2f80014.png)

**Comment by kcullion** [comment]
When rejecting an application with postman, I see this card - so perhaps some of this was already done. I think it's just the progress bar that needs updating 
![image](https://user-images.githubusercontent.com/18424138/132392364-506bff82-eec2-4cf0-94b9-a4511909348e.png)

**Comment by kcullion** [comment]
closing this ticket as it has been fixed as part of another ticket. Dashboard card on QA is now correct: 
![image](https://user-images.githubusercontent.com/18424138/134236091-94272209-05fd-45d5-8904-60c99fea90c4.png)
