### ISSUE TITLE
[UI]: Application Section E: Ethics Form: Table, actions, upload files & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#22]
**Goal:** To build Section E: Ethics: form, validation, empty ethics letter table+full table views + file upload

**Zeplin links:**
Applicant chooses option 1: https://zpl.io/29mmLkB
Applicant chooses option 2, with empty table: https://zpl.io/VYqqeye
Error state when not uploading a file: https://zpl.io/ad33gDE
Uploaded files table: https://zpl.io/bPEEe5m

## Expected Outcomes
- [x] 1. Instructions
- [x] 2. Warning note (see https://argo-ui-storybook.netlify.app/?path=/story/uikit-notifications-banner--basic)
- [x] 3. Add ethics form with radiobutton options. If the applicant chooses option 1, this form is considered valid and complete.

**Applicant chooses option 2:** 
This is similar to what was done in Section C, but with a file upload instead of a modal form. 
- [ ] 4. A new form element appears with empty file table: https://zpl.io/29mmLkB
- [ ] 5. Upload File button with the upload flow working 
- [ ] 6. When a file is uploaded it gets displayed in a table with the date updated date: https://zpl.io/bPEEe5m
- [ ] 7. Actions: delete file - which, when clicked, will eventually have a confirmation modal similar to the "Remove User" modal in the ARGO section mentioned above). This will remove the file reference from the table.

**Local Validations**
 - [ ] 8. If the applicant doesn't upload a file, then they see this empty table area and button red and error message
 https://zpl.io/ad33gDE
 - [ ] Validations for file upload: Has to be a pdf, doc, docx.  |  Max file size: 200MB @rosibaj confirming if this is right?

![image](https://user-images.githubusercontent.com/18424138/118022188-13602b00-b32a-11eb-92b5-1ce87ee5f740.png)

![image](https://user-images.githubusercontent.com/18424138/118024045-3be92480-b32c-11eb-874d-94c8e46141a8.png)

![image](https://user-images.githubusercontent.com/18424138/118024107-4dcac780-b32c-11eb-9b07-efe7a29550be.png)

![image](https://user-images.githubusercontent.com/18424138/118036652-d2bcdd80-b33a-11eb-8fa8-359c1bc1899e.png)

**Comment by caravinci** [comment]
Preparing an initial version, which includes the base layout and the radio buttons disabled.
This, in order to hasten an MVP deliverable. Will address the pending checks at a later stage.

**Comment by rosibaj** [comment]
Will abstract ticket tasks out to followup ticket once base in QA

**Comment by kcullion** [comment]
Looks good to me as the basic UI there! moving to Awaiting release

**Comment by rosibaj** [comment]
for record - followup tickets:
https://github.com/icgc-argo/dac-ui/issues/141
https://github.com/icgc-argo/dac-ui/issues/58
