### ISSUE TITLE
[UI+Data Hookup + Backend] Removing section F IT and moving checkboxes to Data Access Agreement

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#226]
For

- [ ] UI
- [ ] pdf
- [ ] backend

we need to make the following updates

- [ ] remove Section F for IT Agreements
- [ ] rename Section G DAA to `F. Data Access Agreement`
- [ ] rename Section H Appendices to `G. Appendices`
- [ ] Move the IT checkboxes to the new F. Data Access Agreements and change the title for these checkboxes to `You MUST agree to the following procedures in order to have access to the ICGC Controlled Data:`

So the new checkboxes for section F should look like:

![image](https://user-images.githubusercontent.com/18424138/126185659-779e01f8-8d1c-4581-9363-9d20efdde81a.png)

**Comment by rosibaj** [comment]
Tested with DACO 112 - looks great. thank you @anncatton @blabadi !!

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
