### ISSUE TITLE
[UI]: Application Section F: IT Agreement Form & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#23]
**Goal:** To build Section F: IT Agreement section with the agreement validation.

Zeplin: https://zpl.io/bL99vpm

## Expected Outcomes
- [x] 1. Set up all content with proper styles
- [x] 2. Integrate form checkboxes. 
- [x] Local validation for the required checkboxes should work. See error state for checkbox component on this mock: https://zpl.io/2EQQ5vx

![image](https://user-images.githubusercontent.com/18424138/118041111-66dd7380-b340-11eb-838d-25a433044afd.png)

**Comment by kcullion** [comment]
@caravinci we just got confirmation from Amber that we can remove this portion about the cloud access. Should we just go ahead and do that as part of feedback for this ticket @rosibaj ?
![image](https://user-images.githubusercontent.com/18424138/122231898-d3d8b180-ce88-11eb-9254-92939ef33d41.png)

**Comment by caravinci** [comment]
So, just to confirm: remove the whole `CLOUD STORAGE ACCESS AGREEMENT` section, including instructions and the 2 checkboxes? if so, consider it done. Will include the changes in the next deployment.

**Comment by rosibaj** [comment]
@caravinci yes, that is correct. remove this section from UI completely

**Comment by kcullion** [comment]
@rosibaj should @blabadi remove it from the API too? (The cloud agreements)
![image](https://user-images.githubusercontent.com/18424138/122253661-5ddd4600-ce9a-11eb-8093-c3b68e4e0d30.png)

**Comment by blabadi** [comment]
Yeah @kcullion backend validates that these agreements were accepted to allow submission

**Comment by kcullion** [comment]
ok thanks @blabadi ...please remove those from the backend. Let me know if you want me to make a ticket for that

**Comment by kcullion** [comment]
Discussed with @caravinci and the css was tricky to make the shading go under the numbers (for the zebra striping) - we agreed it's fine to just have the shading under the copy block only (for this section and the Data Access Agreement section)

**Comment by rosibaj** [comment]
This section looks good to me, pending any feedback from @kcullion !

**Comment by kcullion** [comment]
Looks good to me too! Moving to awaiting release
