### ISSUE TITLE
[UI]: Application Section G: Data Access Agreement Form & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#24]
**Goal:** To build Section G: Data Access Agreement section with the agreement validation.

Zeplin: https://zpl.io/2EQQ5vx

## Expected Outcomes
- [x] 1. Set up all content with proper styles 
- [x] 2. Integrate form checkboxes. 
- [x] 3. Local validation for the required checkboxes should work. 

![image](https://user-images.githubusercontent.com/18424138/118041819-4661e900-b341-11eb-8e0e-7962cf7d766e.png)

**Comment by rosibaj** [comment]
This section looks good to me, pending any feedback from @kcullion !

**Comment by kcullion** [comment]
Looks good to me too! Moving to awaiting release
