### ISSUE TITLE
[ContentUpdate] Introduction/Terms section

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#240]
Amber has approved the Application terms section. Please make the following changes

- [x] Change the title of this section from Introduction to Application Terms
![image](https://user-images.githubusercontent.com/18424138/128363610-c2dbac7b-6d6b-4701-8bb1-16870c484d3f.png)

- [x] Update the content to what's in the document https://docs.google.com/document/d/1DLJoqiDTXsoZ1LKpMK3pfJr5RUtJIomwoiR08pnZ_B4/edit#heading=h.73su5dklkmvv
- [x] these changes should be reflected on the UI and the pdf

We are still waiting on the link URL in this sentence The ICGC DACO approved projects are posted on the `ICGC ARGO website`. I've included that to be updated in this ticket: https://github.com/icgc-argo/dac-ui/issues/164

**Comment by kcullion** [comment]
looks good, thanks @caravinci

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
