### ISSUE TITLE
[ContentUpdate] Ethics Section

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#241]
Just so I don't forget...making these notes for content changes. Will update with all changes when content is approved

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/7b2d2c6b-339c-49e9-9bb9-ee7f92652f76)

- [x] Update the text to match this document for the ethics section: https://docs.google.com/document/d/1DLJoqiDTXsoZ1LKpMK3pfJr5RUtJIomwoiR08pnZ_B4/edit#heading=h.xa2lzvx7nct0 
- [x] Remove the link to Data Access Agreement (should not be link)

**Comment by rosibaj** [comment]
lgtm thank you @caravinci !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
