### ISSUE TITLE
🐛 Application State on UI is not changing 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#243]
## Describe the bug
When I finish my application and the sign and submit section is enabled, the UI does not automatically change the application state for me. Even when I navigate to the Sign and Submit section, I still see the application in Draft. The whole header object does not update on page action (only on refresh)

![image](https://user-images.githubusercontent.com/18424138/126520541-4f04d66c-b789-4e5e-a347-20276f7072bd.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Complete an application
2. look at the header bar state label and download button label. This should change once that sign and submit section gets enabled. 
3. It stays as "DRAFT" even though it should be in "SIGN AND SUBMIT" state
4. Also if I make the form invalid, it stays in "SIGN AND SUBMIT" state unless I refresh.

## Expected behaviour
I shouldn't have to refresh to see the header update. It should happen automatically like the enable/disable of the sign and submit section.

**Comment by kcullion** [comment]
I now see the header refresh automatically, which is so helpful - thanks @samrichca 
I found it didn't refresh on submit application but we discussed it's because of an event that's not triggered on the modal and will be taken care of here: https://github.com/icgc-argo/dac-ui/issues/288

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
