### ISSUE TITLE
🐛 Unexpected Error happened again - related to ethics?

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#246]
## Describe the bug
I got that unexpected error again.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. I filled out sections A, B, D 
2. I went to ethics and chose option 1
3. then I went to section F and got this
![image](https://user-images.githubusercontent.com/18424138/126515003-c4e0fe35-ca6b-420c-bd5b-294e27d51599.png)

## Expected behaviour
This error should not occur.

**Comment by rosibaj** [comment]
@kcullion can  you attempt to replicate 6this again? 

I think you may have been caught mid-deploy for the api which interfered!

**Comment by kcullion** [comment]
thanks @rosibaj I will refresh and try with a new application

**Comment by kcullion** [comment]
@rosibaj I think that's the case..I will close this ticket but found a diff bug I logged: https://github.com/icgc-argo/dac-ui/issues/248
