### ISSUE TITLE
[UI]: Application Section H: Appendices Form & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#25]
**Goal:** To build Section H: Appendices section with the agreement validation.

Zeplin: https://zpl.io/aR444oN

## Expected Outcomes
- [x] 1. Set up all content + instructions with proper styles
- [x] 2. Integrate appendices and agreement checkboxes. 
- [x] 3. Each appendix will have an external link that will link to a policy page on icgc-argo.org. Links TBD (open in a new window)
- [x] Local validation for the required checkboxes should work. See error state for checkbox component on this mock: https://zpl.io/2EQQ5vx

![image](https://user-images.githubusercontent.com/18424138/118042437-12d38e80-b342-11eb-95be-7474c1427ca4.png)

**Comment by rosibaj** [comment]
Tested June 17, 2021, 5:02: 
we seem to have a click conflict - if i click the link inside the checkbox text, it does two things
- opens the link
- selects/deselects the checkbox.  @kcullion as the link to the appendix is directly above, do we really need to repeat the link in the checkbox text?

**Comment by kcullion** [comment]
@rosibaj when I click the link, it doesn't select the checkbox - it just opens the link. 

I think in this case, we can remove those links from the checkbox, but do we want to handle the case where there may be a link in the checkbox? Actually let's cross that bridge when we get new content. 

for now @caravinci please

- [ ] remove the links to the appendices from the checkboxes

**Comment by caravinci** [comment]
The reason you're experiencing different results when testing that issue is related to the outdated version of React used in Uikit... React@16. Their event bubbling was resolved sometime last year with React@17, so we won't have an easy fix until the package is updated.

Removing the links for now. :+1:

**Comment by rosibaj** [comment]
hmm @kcullion I retested: 
- windows/chrome has the click issue i described
- windows/firefox does NOT have the issue i described above
- it sounds you in mac/chrome do NOT have the issue described above.

**Comment by kcullion** [comment]
@rosibaj interesting. Removing the links for now solves this :)

**Comment by caravinci** [comment]
Indeed, changes made.
Pending further feedback from any other sections to open a PR.

**Comment by rosibaj** [comment]
lgtm thank you @caravinci
