### ISSUE TITLE
🐛 Change the date on approve to 2 years in the modal

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#251]
![image](https://user-images.githubusercontent.com/15824252/126526858-3ab0b295-11d0-4a73-a381-4feca3a6a700.png)

**Comment by kcullion** [comment]
Tested Jul 22 and I now see the end date is after 2 years. thanks @samrichca 
![image](https://user-images.githubusercontent.com/18424138/126659579-f1806637-d166-4c84-8341-8c9db5c1f0f4.png)
