### ISSUE TITLE
🐛 DACO REVIEW state - should lock all sections

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#253]
## Describe the bug
When I submit the application, I should not be able to use the radio buttons in the ethics section

![image](https://user-images.githubusercontent.com/18424138/126532827-ee252f5b-68cd-4f63-9c60-844d362190ae.png)

- [x] Collaborators should be locked, so all actions should be disabled:
![image](https://user-images.githubusercontent.com/18424138/126700218-eb8f9570-9d08-43ff-9072-27eb2dbfe404.png)

- [x] Sign and Submit is locked - actions are disabled
confirmed that the actions are disabled on this section in REVIEW state.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Submit an application
2. go to ethics section
3. go to sign and submit section

## Expected behaviour
The user shouldn't be able to revise any section of the form.

**Comment by ciaranschutte** [comment]
https://github.com/icgc-argo/platform-ui/pull/2007
need to merge this.

**Comment by rosibaj** [comment]
Looks mostly good 
- ethics section is locked now correctly looks great
- logged an issue with delete in collaborators in locked state https://github.com/icgc-argo/dac-ui/issues/314 as follow-up ticket
