### ISSUE TITLE
🐛 DACO ADMIN - change end date in modal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#254]
## Describe the bug
This should be two years later now

![image](https://user-images.githubusercontent.com/18424138/126533633-f786ad2e-dbfc-4416-b2f2-a63770c98191.png)

**Comment by rosibaj** [comment]
@kcullion i think i logged this bug already

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/dac-ui/issues/251
