### ISSUE TITLE
[UI]: Application Section I: Sign and Submit with single file upload & Validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#26]
**Goal:** To build the final "Sign & Submit" section, file upload, validation

**Zeplin links:**
No file uploaded: https://zpl.io/bL999dM
File uploaded: https://zpl.io/2GjjjAE

NOTE: THE INSTRUCTIONS SHOULD BE 1, 2, 3 NOT 1, 2, 4.  oops

## Expected Outcomes
- [ ] 1. Instructions
- [ ] 2. `Finalized pdf` button - will eventually download the finalized application to sign
- [ ] 3. External links open in a new window: https://www.docusign.ca/ and https://acrobat.adobe.com/us/en/sign.html
- [ ] 4. Implement file upload form.
- [ ] 5. Submit application button - this is disabled until the applicant uploads a pdf file.
- [ ] 5b. Next button behaviour...include the next button in section H but disable it until this sign and submit section is available.

**Local Validations**
 - [ ] Validations for file upload: Has to be a pdf |  Max file size: 200MB 

**Applicant uploads a file:** 
https://zpl.io/2GjjjAE
- [ ] 6. When a file is uploaded it gets displayed in the spot where the upload file button was with the file name and updated date. 
- [ ] 7. Actions: delete file - which, when clicked, will eventually have a confirmation modal similar to the ethics file removal flow. This will remove the file reference from the page and replace with the "upload file" button again.
- [ ] 8. When the applicant has uploaded a pdf file, this button is enabled

![image](https://user-images.githubusercontent.com/18424138/119178475-ca039000-ba3b-11eb-9c3c-a652871c4b5c.png)
![image](https://user-images.githubusercontent.com/18424138/119674495-3c90b900-be0a-11eb-81d9-260a363c9ec4.png)

![image](https://user-images.githubusercontent.com/18424138/119178586-ea334f00-ba3b-11eb-8d24-9fa1a88697b8.png)

**Comment by rosibaj** [comment]
@ciaranschutte a couple small edits: 
- [ ] update link color; 
![image](https://user-images.githubusercontent.com/15824252/125519705-9132aede-6d2b-4348-a914-64c4c0aafc0e.png)
 
- [ ] Open these links as a new tab: 
![image](https://user-images.githubusercontent.com/15824252/125519795-fd5ef1db-d720-4050-b7ff-b2919dbf5baa.png)
- [ ] display issue on the PDF name when loading the sign & submit section. 
![image](https://user-images.githubusercontent.com/15824252/125520276-334c78da-d8fa-47bc-bff7-9a93f6faba0a.png)

**Comment by rosibaj** [comment]
feedback for this one was moved to #59
