### ISSUE TITLE
*Application Section B: Address same as applicant checkbox.*

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#262]
- [ ] **Application Section B: Address same as applicant checkbox.**
If the applicant checks off the "Address is the same as applicant" checkbox in section B, then 
1. Disable the address fields in Section B 
2. If any address fields have values in section A, show those in the disabled fields in section B 
3. If no values are filled out in the address fields in section A, only those need to report the errors for required fields (not the disabled fields in section B)

ui needs to fetch the data from the other sectio in this case

**Comment by rosibaj** [comment]
@kcullion can you add the zeplin for the screen on this ticket?

**Comment by kcullion** [comment]
@samrichca this is the zeplin for this section: https://zpl.io/bz3mDAX
But when the checkbox is checked, the fields just have the regular disabled styling that's already been implemented

**Comment by kcullion** [comment]
tested on QA July 26 and it's working very well, thanks @samrichca !
