### ISSUE TITLE
[UI] Implement loader state for Upload PDF button

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#269]
If the file upload takes longer than a few seconds, it seems there's an issue. 

Let's implement the loader icon / state for this button - like the download pdf button has. (label can remain as "Upload a File"
![Screen Shot 2021-07-22 at 11.49.11 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/ed8ee049-edb3-47db-b3cc-66666afa77fe)

- [x] implement loader state for Ethics upload
- [x] implement loader state for sign and submit upload

**Comment by kcullion** [comment]
tested in QA. I see the loader for both file uploads. Thanks @ciaranschutte

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
