### ISSUE TITLE
[UI] When APPROVED disabled sign and submit actions (applicant and admin) and collaborator actions (for admin only)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#275]
- [x] Please disable the trashcan and the submit button when the application is in APPROVED state?

NOTE: this is both for the Applicant and the DACO Admin view of the application

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/2a8e8410-96bb-4552-a637-1df0f6cce5e9)

- [x] For MVP we will also have the application locked for ADMIN when APPROVED. Can you also disable these actions for an APPROVED application (FOR ADMIN ONLY)
![image](https://user-images.githubusercontent.com/18424138/126705568-7830bcc5-d47e-4716-bb4d-8298c4a1c779.png)

**Comment by ciaranschutte** [comment]
verified in dev

**Comment by kcullion** [comment]
tested in QA jul 28. looks good @ciaranschutte !

- I see collaborators and sign and submit disabled for ADMIN when approved
![image](https://user-images.githubusercontent.com/18424138/127354883-936364d0-8090-4484-85d6-f0631311268f.png)

- I see sign and submit disabled for applicant when approved. But collaborators are unlocked and enabled (which is expected)
![image](https://user-images.githubusercontent.com/18424138/127355088-1d1fbddb-6530-4e90-8f7e-ce69a3a50bde.png)
