### ISSUE TITLE
Dashboard Application Card order

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#279]
Let's order the dashboard application cards by "Last updated" date/time. So the most recently updated will show first
![image](https://user-images.githubusercontent.com/18424138/126803141-44d43d61-1ab0-4f4a-a4cd-7bf220f12d20.png)

**Comment by kcullion** [comment]
I see this order in QA now. Thanks @ciaranschutte !

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
