### ISSUE TITLE
Trigger a refresh on submit application confirmation modal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#288]
When the user confirms they want to submit their application, trigger a reload so that the state changes from SIGN AND SUBMIT to DACO REVIEW in the header. 

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/e2a22c27-216c-49ab-9d35-414d44343c07)

This was done with the request revisions modal, for instance. You can see once you "send request", the application goes from DACO REVIEW to REVISIONS REQUESTED state.

**Comment by kcullion** [comment]
Tested in QA July 28
When I submit the application now, the page refreshes and I see the new application state (DACO Review) and a locked application. Working as expected, thanks @samrichca

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
