### ISSUE TITLE
[DATA Hookup] - Table Search

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#29]
Connect the SEARCH bar to the table list 

![image](https://user-images.githubusercontent.com/18424138/117189385-257f1e00-adac-11eb-8fb5-0596e92c54c1.png)

- [ ] Should filter the table as the admin types search keyword
- [ ] Should filter across the paginated table (not just the items you see in the table "page" you are on)****

**Comment by kcullion** [comment]
As discussed in sprint planning, we may save this feature for the end/implement post-mvp

**Comment by kcullion** [comment]
@anncatton this works great!
@rosibaj can you have a look at this too? 
The only thing I notice (and it wasn't part of this ticket) is there's no "no results" message when the search returns no results. But I feel like in this context that's ok right? Is it worth doing?

**Comment by rosibaj** [comment]
@kcullion i think it looks fine. its pretty obvious still (everything says 0) and its an interactive search... we can make alow priority no search results ticket for backlog

**Comment by rosibaj** [comment]
@anncatton this works great! so helpful from the table!

**Comment by kcullion** [comment]
the search works in staging!
