### ISSUE TITLE
🐛 [UI] Add the "Revisions Requested" flag to the UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#299]
## Goal
After a discussion in sprint planning, we will add a "Revisions Requested" flag to the UI when an application is in revisions mode. And keep the progress bar consistent with the labels when filling out an application.

The API ticket: https://github.com/icgc-argo/dac-api/issues/160

## Application Outcomes
When the application is in `Revisions Requested` state: https://zpl.io/29GZjLl
- [x] Keep the progress bar as the usual "Draft | Sign & Submit | DACO review", starting in draft state
- [x] Add the `Revisions Requested` flag above the progress bar.
![image](https://user-images.githubusercontent.com/18424138/131377897-5f0fa4c0-0b1a-49dd-8e1a-a3871bd7f155.png)

- [ ]  Remove this flag once the revised application is submitted and in `DACO Review` state. 
![image](https://user-images.githubusercontent.com/18424138/131379350-899a66a9-b9b7-4e30-b03b-a8d954dfb72b.png)

- [x] DACO Admin should see this flag too for the applications that are in Revisions requested state

## Dashboard Card revisions
For the Dashboard card when in Revisions Requested state: https://zpl.io/Vx3zv5R
- [x] Keep the progress bar as the usual "Draft | Sign & Submit | DACO review", starting in draft state
- [x] For the status - highlight it in red font. 
- [ ] Change the status to `Reopened for revisions. Revision details were sent via email.
`
![image](https://user-images.githubusercontent.com/18424138/131380004-7ca27f27-7d70-4fa7-be52-0b77d88dd1cb.png)

**Comment by ciaranschutte** [comment]
@kcullion we need to add to the API to support this. a "revisions made" state to track a signed app after requested revisions

**Comment by kcullion** [comment]
oh ok...I think this was a ticket for @anncatton and she said it was a frontend thing. Let's discuss when she's back

**Comment by rosibaj** [comment]
blocking ticket is now completed

**Comment by samrichca** [comment]
![image](https://user-images.githubusercontent.com/3540896/134049987-1f38b6fe-1168-4f2f-8617-a072ae145968.png)
![image](https://user-images.githubusercontent.com/3540896/134051659-92a84c3a-37da-4da6-9a76-d30345f3ae0d.png)

![image](https://user-images.githubusercontent.com/3540896/134050041-9821f673-997a-487a-b811-e8c143ffb5ac.png)
![image](https://user-images.githubusercontent.com/3540896/134050092-e8281b36-c1d1-48ba-b066-4bcf50469c2e.png)

- add request revisions flag to progress bar in the header in revision & submit states when revisions were requested
- only show submitted banner in review state
- in the dashboard card, make status text red & update copy

**Comment by rosibaj** [comment]
looks excellent! thank you @samrichca !
