### ISSUE TITLE
Login, Permissions and Routes

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#3]
@rosibaj commented on [Fri Apr 23 2021](https://github.com/icgc-argo/roadmap/issues/767)

## Login permissions and routes 

1. **DACO Applicant Dashboard** 
URL: daco.icgc-argo.org/applications/ 
(DACO ADMIN and APPLICANT see different displays on their dashboards)
- applications render based on a users ego-id/email

2. **DACO Admin Dashboard** 
URL: daco.icgc-argo.org/applications/ 
Scope: DACO-REVIEW.WRITE // can see all applications and update them

3. **Application Page** 
URL: daco.icgc-argo.org/applications/{APP-ID}

## UI Portion for Logged in header
- [x] Logged in: https://zpl.io/bz3EN0z
- [x] Logged in with User dropdown for logout: https://zpl.io/bW8zNzk

![image](https://user-images.githubusercontent.com/18424138/117061421-28b4d400-acf0-11eb-8fb7-31c2ba4a1cd8.png)
The menu states can be found in this zeplin: https://zpl.io/bW8zNzk
1. Menu hover state
2. Menu default state
3. Menu active state - this is really the only section that will ever be active as the other sections are external links.
4. When clicking on the user name, a dropdown will appear with a link to logout (similar to the ARGO Platform, but we will not have a user profile page for MVP)

**Comment by anncatton** [comment]
PR will include login/logout functionality, as well as redirecting the user to the home page when their jwt expires
No page content yet so logged in state is only testable with the NavBar

**Comment by anncatton** [comment]
@kcullion I removed the DNA Loader on this ticket, it needs to be added a little differently than I had it. Sorry for the back and forth!

**Comment by kcullion** [comment]
No worries @anncatton! The loader may need to be in other places too, do you think it's worth me making a ticket for later to implement it?

**Comment by anncatton** [comment]
Maybe? I wanted to ask @ciaranschutte what he thought would be a good approach. At least, we can set up a ticket with where we're planning on needing loaders!

**Comment by rosibaj** [comment]
@anncatton a couple comments: 
- text on button change:
![image](https://user-images.githubusercontent.com/15824252/120202141-3b89ce00-c1f4-11eb-895c-071ea5c537e2.png)
- [ ] the redirect is a little slow and shows the un-logged in state while I'm waiting.  Is this the loading behavior you were saying would need to be in another ticket?

**Comment by anncatton** [comment]
Yep @rosibaj we removed the loader in this one so it just looks delayed while the request to ego happens. I think we just need to make a ticket for it.

**Comment by rosibaj** [comment]
thanks for confirming @anncatton - #81 made for next sprint.
