### ISSUE TITLE
[UI] Homepage - update ARGO logo 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#303]
We need to update the ICGC ARGO logo to this main logo with tag line. Ask Kim for the file

- [x] I put it in the design and in order to make it legible it should be around 200px width. 
- [x] This means we should increase the width of the ICGC 25K logo (around 165px width)

So it will look something like this: 
![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/99065320-e4e8-41f6-bd75-b8b5ba77b1ad)

**Comment by rosibaj** [comment]
lgtm thank you @samrichca !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
