### ISSUE TITLE
🐛 Email validation: trim whitespace before showing error

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#304]
## Describe the bug
Amber was finding:
It wont accept my institutional email (which is different to the google webmail address I used to log in). See below. 
![image](https://user-images.githubusercontent.com/18424138/127526614-3eaf32a1-4c99-41c9-9ec6-ebf70b8a14a0.png)

So she is seeing the error but not going back and clicking on that field for the whitespace to be removed for her. This is preventing her from finishing the application. 

## Expected behaviour
We need to 

- Trim the whitespace and return characters
- Then check for valid email
- Then save

**Comment by rosibaj** [comment]
lgtm - i was able to paste an email with whitespace and have it trim and validate as expected.
