### ISSUE TITLE
🐛 Word count not showing on Project Summary section on load

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#313]
- fill out project summary section. leave one firled with > 200 words 
- click to another section then click back
- you can see the workd counts are all 0, and only appear if you start typing again 
- 
![image](https://user-images.githubusercontent.com/15824252/127657678-7de2afc3-d92e-4c3d-a056-d9ed0129828a.png)
![image](https://user-images.githubusercontent.com/15824252/127657839-959f5c88-8954-4f11-a15f-e61e473450d4.png)

## Expected behaviour
should show the correct word count.

**Comment by caravinci** [comment]
Pending on merge of this PR https://github.com/icgc-argo/platform-ui/pull/2005

**Comment by rosibaj** [comment]
thanks @caravinci i thought this was taken care of but couldn't find it! sounds good!

**Comment by rosibaj** [comment]
looks great thank you!

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
