### ISSUE TITLE
🐛 Should not be able to delete or edit collaborators while the application is in REVIEW state 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#314]
![image](https://user-images.githubusercontent.com/15824252/127660355-60e697af-0004-44c7-a244-288be7a1008e.png)

## Expected behaviour
When in review, collaborators should not be able to be deleted or edited.  Actions should be disabled.

**Comment by kcullion** [comment]
looks good, thanks @ciaranschutte ! moving to awaiting release

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
