### ISSUE TITLE
[Validation] Collaborators emails added first, cannot be same as PI emails added second

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#329]
As an edge case to this ticket: https://github.com/icgc-argo/dac-ui/issues/142

- [ ] If the form submitter adds a collaborator first, then adds the same email address within section A for the PI - then section C should report an error. 

- [x] Let's do the same thing you did with the primary affiliation validation on the table - shade that row of the collaborator with the error. 

![image](https://user-images.githubusercontent.com/18424138/128204710-b852427a-d8a4-4d09-83e5-5b5771b98510.png)

- [x] When the submitter edits the collaborator, they will see the error reported on the email field(s) saying `The applicant does not need to be added as a collaborator`.

**Comment by akachru-github** [comment]
New API work required to complete this. @kcullion to create a new ticket for the API work.

**Comment by kcullion** [comment]
API ticket created for this: https://github.com/icgc-argo/dac-api/issues/151
Can test some more once that is implemented as the UI should just work

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
