### ISSUE TITLE
[Content Updates] Appendices 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#330]
Please revise the list of appendices to only include these on the UI and the pdf:

- [ ] APPENDIX I
Title: APPENDIX I - ICGC ARGO Goals and Policies
Link: https://www.icgc-argo.org/page/72/introduction-and-goals- 
ID: stays the same at appendix_icgc_goals_policies
- [ ] APPENDIX II 
Title: APPENDIX II - Data Access and Data Use Policies and Guidelines
Link: https://www.icgc-argo.org/page/132/data-access-and-data-use-policies-and-guidelines
ID: Change to: `appendix_data_access_policy`
- [ ] APPENDIX III 
Title: APPENDIX III - Intellectual Property Policy
Link: https://www.icgc-argo.org/page/78/e4-intellectual-property
ID: Change to: `appendix_ip_policy`

related API ticket is here: https://github.com/icgc-argo/dac-api/issues/136

**Comment by kcullion** [comment]
changes look good, thank @anncatton !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
