### ISSUE TITLE
🐛 Cannot add collaborators when space in email address fields 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#334]
- space trimming not working in collaborator modal 
- when adding a space, it doesn't allow to submit the form. Nothing happens, no error
- This was noticed in staging
![image](https://user-images.githubusercontent.com/15824252/128236753-29ba66d8-922b-47dc-ac94-fc0e2409e20f.png)

**Comment by caravinci** [comment]
The error handling for this case (e.g. showing some message when API rejects a request, rather than failing silently) is being added in #328.

I'll focus this here ticket on not allowing a request to be made to begin with.

**Comment by kcullion** [comment]
this works for me now, thanks @caravinci !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
