### ISSUE TITLE
Error banners for collaborators - remove the x

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#338]
as feedback to: https://github.com/icgc-argo/dac-ui/issues/142

Can you just fix:
- [x] remove the "x" on the banners - they are not dismissible, and it's not working right now
![image](https://user-images.githubusercontent.com/18424138/128389405-932a7b63-c336-4b4e-a862-3329a6ffb456.png)

**Comment by kcullion** [comment]
looks good, thanks @ciaranschutte !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
