### ISSUE TITLE
[Content Updates]Application Terms section fixes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#345]
- [x] Add a period at the end of this paragraph
- [x] link the text shown in the screenshot - open in a new tab: https://www.icgc-argo.org/page/72/introduction-and-goals
![image](https://user-images.githubusercontent.com/18424138/128523180-9e5480bb-4165-41ad-a20b-87416418cef0.png)

- [x] Fix the styling for this new content within the pdf. The list styling has been removed so it looks like this. You will probably need to add some spacing below the lists too so the content looks more like the UI section
![image](https://user-images.githubusercontent.com/18424138/128523566-7be0e5e5-5f69-4b62-96ee-49aa8eb1f422.png)

**Comment by kcullion** [comment]
Tested in QA Aug 11. Looks good @caravinci !

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
