### ISSUE TITLE
[UI] Table of contents completion behaviour

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#346]
This was working as expected, but now something has changed in QA.

With this ticket https://github.com/icgc-argo/dac-ui/issues/191 we made the table of contents less aggressive, which is working well.

But now when the user completes a section, the section does not get checked off until they leave that section. So if they finish the last section, the sign and submit section gets enabled correctly, but that section they just finished is not checked off until they move to a different section. 

![image](https://user-images.githubusercontent.com/18424138/128524949-f6693018-3222-43b2-9483-e4bb59c4628c.png)

Note: the last sign and submit section is working as expected - once I upload the pdf, the section gets checked off as completed.

## Expected behaviour
It seemed more intuitive before when the user didn't need to move away from the section for the checkmark to appear in the table of contents. The error behaviour is still good though.

To see an example of this, interact with an application that is open for revisions. Once the user makes a change in that section, the pencil turns from orange to green without requiring the user to move away from the section
![image](https://user-images.githubusercontent.com/18424138/128526155-9952e67a-594b-49e6-b8e7-5b7357ce8d7f.png)

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
