### ISSUE TITLE
[UI] Add loading state to the submit confirmation button

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#353]
When submitting an application - let's add the button loader state to this so it looks like something is happening. like you did here: https://github.com/icgc-argo/dac-ui/issues/269

(keep the "YES, SUBMIT" text and just add the loader icon

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/e7bd8d45-abff-4faf-aae5-54a947bc8314)

**Comment by kcullion** [comment]
I see the loader in QA when I submit an application. Thanks @ciaranschutte

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
