### ISSUE TITLE
🐛 Submitting an application sometimes doesn't work - transitions application to sign and submit

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#354]
## Describe the bug
Amber has logged this bug, using Firefox 89.0

`I still can't submit an application- I refresh and it just keeps reloading the sign and submit page. Is this tied to the known bug (being kicked out a lot)? I did receive the email notification though that it had been submitted!`

@samrichca:
`i think the reload issue can be resolved by changing how we handle modals. the changes i added to the header to pick up data from the page, and the page reload triggered by the modals, might be redundant now`

## Expected behaviour
The application should always transition to DACO Review state on the UI when the user submits.

**Comment by akachru-github** [comment]
Need some clarifying info from Amber:
- is she reloading after submission, or is the page reloading herself? Perhaps she can update her version of firefox.
- can she try with Chrome?
- @samrichca  can provide steps to get error from Firefox dev tools.

**Comment by kcullion** [comment]
as discussed on slack @ciaranschutte 
- I tried staging in firefox and before submitting the application I see this error. 
![image (81)](https://user-images.githubusercontent.com/18424138/129243237-6e875ef3-150e-4b74-9f8a-865778a833d6.png)
- Justin thinks his fixes that he's pushing to QA may fix this. 
- So we shall hold on this for now and get Amber to test with a new application when we push to staging next.

**Comment by kcullion** [comment]
Closing this ticket. Amber just wasn't noticing that the application was submitted so I have made this ticket to make it more clear with a success banner: https://github.com/icgc-argo/dac-ui/issues/379
