### ISSUE TITLE
🐛 Country value disappears

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#361]
## Describe the bug
For both country fields, I select a value then fill out the rest of the values and the country value disappears. It seems to save after the second time I enter it

## Expected behaviour
The country value should not disappear

**Comment by kcullion** [comment]
tested in QA Aug 12 and the country is now saving. thanks @caravinci

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
