### ISSUE TITLE
🐛 Removing collaborator: modal pulls in "Undefined" as name

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#364]
## Describe the bug
I filled out an application and approved it. 
On the approved application, I removed a collaborator - the modal is pulling in "undefined undefined" as first and last names

![image](https://user-images.githubusercontent.com/18424138/129098250-e331f8e5-01d0-4ce1-b434-b17eca384b35.png)

## Expected behaviour
It should be behaving like when you remove a collaborator from an application in DRAFT state:
![image](https://user-images.githubusercontent.com/18424138/129098418-cc4f19bf-8eae-4c79-8d19-421ac7ccca4d.png)

**Comment by caravinci** [comment]
Solved with changes made in #329

**Comment by kcullion** [comment]
tested in QA Aug 12 - I see the collaborator name again, thanks @caravinci 
![image](https://user-images.githubusercontent.com/18424138/129264709-afaebc53-06ee-4964-ac70-43b26dabc762.png)

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
