### ISSUE TITLE
[UI+Data Hookup]Closing an application- PRE-APPROVAL 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#369]
## Goal

As a DACO applicant, I can close an application BEFORE it's been approved, and after confirming this action I cannot reopen it. The application will go from `DRAFT` or `SIGN & SUBMIT` state to `CLOSED` state, and remains closed.

API ticket for this: TBD

## Application flow before submitted
- [x] Implement the "Close Application" button (or unhide it) - when in the following states: `DRAFT`, `SIGN AND SUBMIT`, `REVISIONS REQUESTED`
![image](https://user-images.githubusercontent.com/18424138/129249347-5cd4fdb3-c7cc-4af1-b3bc-29c7d20b4028.png)

- [ ] When the applicant clicks on this button when in any of these states: `DRAFT`, `SIGN AND SUBMIT`, `REVISIONS REQUESTED`, show this confirmation modal: https://zpl.io/2Gqj8xd

![image](https://user-images.githubusercontent.com/18424138/130087606-e60d8d6c-1c29-45a6-9aeb-0a3c28d583b0.png)

When the applicant clicks "Yes, Close" button, transition the application to the closed state which includes
Zeplin: https://zpl.io/bAKRgMn
(IGNORE THE TOAST MESSAGE FOR NOW)
- [ ] 1. closed progress bar shown in header from https://github.com/icgc-argo/dac-ui/issues/123
- [ ] 2. "Close application" button is hidden, but Draft/Finalized pdf button is still available for download (currently the pdf download has disappeared for some reason).
- [ ] 3. All application sections are locked and uneditable. (check the collaborators section)
- [ ] 4. The values should be saved in the application that the applicant had filled out - so if the errors persist, then they can be shown but disabled 
![image](https://user-images.githubusercontent.com/18424138/129252890-22cbe561-18fa-4f0c-820d-6c41c9ebf4c7.png)

## Application flow after submitted

- [ ] When the application transitions to DACO REVIEW state, hide the "Close application" button for the Applicant and for DACO Admin (the applicant will have to contact DACO to discuss cancellation - this is a rare case)
![image](https://user-images.githubusercontent.com/18424138/129251059-9bfd42c0-50ac-42ba-8de6-6226291eeb57.png)

**Comment by ciaranschutte** [comment]
fixing collaborators in https://github.com/icgc-argo/dac-ui/issues/371

**Comment by kcullion** [comment]
@rosibaj testing this in QA, and we can consolidate any feedback for the close flows into this ticket: https://github.com/icgc-argo/dac-ui/issues/442
