### ISSUE TITLE
🐛  Cannot Add title to a collaborator during the EDIT phase.

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#376]
## Describe the bug
- found on staging
- Cannot Add title to a collaborator during the EDIT phase. 

## Steps To Reproduce
1. Add a collaborator and DO NOT include the title. 
2. Edit hte collaborator.  Add a title for the first time. Click the purple Edit collaborator button. 
3.  Once saved, again try and edit the collaborator.  You can see the title is not there. 

Here is a video demonstrating that adding a title only works on the FIRST addition, not during editing a collaborator. 
https://drive.google.com/file/d/1EhIfuLkHDGSOGMsvyYEh2nim5raWKXzp/view

## Expected behaviour
Title should be able to be added on collaborator edit.

**Comment by rosibaj** [comment]
@ciaranschutte im a little confused :) are you saying this is an api issue?

**Comment by kcullion** [comment]
@ciaranschutte @rosibaj this looks to be fixed to me!

**Comment by rosibaj** [comment]
@ciaranschutte can i please get a version label attached to this ticket?

**Comment by ciaranschutte** [comment]
@rosibaj 0.39.0 its an api fix (in case you want to move it to that repo)
