### ISSUE TITLE
[UI] Success banner and submitted application state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#379]
Amber wasn't realizing that her application was being submitted, so let's do the following upon submission:

- [ ] When the user clicks the confirmation "Yes Submit" button and the application transitions to DACO Review state and gets locked, let's take the user to the first page (Application Terms) of the application. 
- [x] Implement the following dismissible success banner above the application. https://zpl.io/aRRmWEp
![image](https://user-images.githubusercontent.com/18424138/129745223-23005054-0825-4a2b-9ac9-cea388813f2d.png)

**Comment by kcullion** [comment]
works well @ciaranschutte 
Can you just make the following style fixes
- [ ] make the banner as wide as the form
- [ ] add a bit more space below the banner so there's equal spacing above and below the banner.
![image](https://user-images.githubusercontent.com/18424138/130833125-9766a28a-ced6-486c-8461-e1b39db6112f.png)

**Comment by ciaranschutte** [comment]
tested  on dev

**Comment by kcullion** [comment]
@ciaranschutte this looks good. Styling is fixed and the status refreshes.

Only thing is we used to have it going back to the first application terms section, now it stays on the sign and submit section. Can you fix that and have it refresh, change to daco review and go back to Application Terms
![image](https://user-images.githubusercontent.com/18424138/131857103-d700624a-1198-4783-86ff-3b1587d08bc5.png)

**Comment by kcullion** [comment]
looks great @ciaranschutte !
