### ISSUE TITLE
[UI] Add expiry date on approved application headers

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#388]
Let's add the expiry date in the header of APPROVED applications:
Zeplin: https://zpl.io/aNYGKKN

- [ ] Will say "Expires: [date]" then include the expiry date of the application
- [ ] Use the same blue as the access expiry item on the approved dashboard card 
- [ ] Reduce the font size of the entire H1 to 16px...so it's not too long

![image](https://user-images.githubusercontent.com/18424138/130498357-26c37dec-3afc-4667-942d-dc73ceb98e55.png)

**Comment by ciaranschutte** [comment]
tested on dev. one small content piece to fix '|' is always displaying

**Comment by kcullion** [comment]
tested in QA. Looks awesome! thanks @ciaranschutte !
