### ISSUE TITLE
[Content Updates] Ethics section - remove French reference

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#392]
From Amber and Ana from some feedback on the documentation copy, they just want English translation.

Update this text to 
If the ethics approval is written in a language other than English, **please upload a translated version**.

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/8efa5fb3-6d6d-415a-ae8d-d084a021eec4)

**Comment by ciaranschutte** [comment]
tested on dev

**Comment by kcullion** [comment]
tested in QA, looks great @ciaranschutte
