### ISSUE TITLE
🐛 Maintenance page shows double header and footer

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#398]
## Describe the bug
The maintenance page: https://dac.qa.argo.cancercollaboratory.org/maintenance
Should just show one header and footer. I'm still seeing this:
![image](https://user-images.githubusercontent.com/18424138/131353818-a224e96a-98af-410c-958b-5de58bbeadb0.png)

**Comment by ciaranschutte** [comment]
removing this as a "page", that's why the error was showing

there will be no way to test on dev/QA without hindering others momentarily.

quickest way:
if you have the project setup locally you can just set the `.env` variable of `NEXT_PUBLIC_MAINTENANCE_MODE_ON=true` to true

**Comment by rosibaj** [comment]
@ciaranschutte is there a version associated to this

**Comment by ciaranschutte** [comment]
@rosibaj  0.25.0
https://github.com/icgc-argo/dac-ui/pull/410/files
didn't update on the board from zenhub :(

**Comment by kcullion** [comment]
The double header and footer are gone! thanks @ciaranschutte 

Question @rosibaj @ciaranschutte - when I go to the maintenance link when logged out, it flashes then goes to the homepage. But shouldn't we be able to access it when logged out since it's likely when the site is down for maintenance?

**Comment by rosibaj** [comment]
@kcullion this is a generic page error; i think its ok to show the logged in items as it is still possible to navigate to those. 

In the event of a real maintenance, i think we would need to set up a second netlify deploy with the maintenance page (like ARGO).  @ciaranschutte can you confirm ^?

**Comment by kcullion** [comment]
Thanks @rosibaj ...I guess then that netlify page should have the /maintenance url and not this generic error page.

**Comment by ciaranschutte** [comment]
@rosibaj Currently maintenance mode is just based on an environment flag.
If maintenance is "we had to take this thing offline for a bit" and not server related we can just toggle the env var.
if maintenance is "completely take down server hosting this stuff" then yes, you are correct, second netlify deploy.
