### ISSUE TITLE
[UI] Warning message for uploading ethics letter with same name as already uploaded

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#403]
API ticket: https://github.com/icgc-argo/dac-api/issues/163

As discussed over slack, let's implement a warning message for when the user tries to upload an ethics file with the same name as one that's already uploaded.

So show a confirmation modal to warn them that their file will be replaced.

## Expected Behaviour before an application is approved. 

1. Say the ethics letters that have been uploaded to a draft application are these:
![image](https://user-images.githubusercontent.com/18424138/131386388-648ac728-6369-4d2f-8ef4-acf0558836c4.png)

2. Then the applicant uploads a file that has the same name as one that's already uploaded. 
- [ ] Show this warning confirmation modal first: https://zpl.io/VQ4mEMA
![image](https://user-images.githubusercontent.com/18424138/131387013-3e88561a-2081-4427-95d6-81da02d394b9.png)

3. When they confirm the upload, replace that old file reference in the table with the new one..like:
![image](https://user-images.githubusercontent.com/18424138/131387594-65a1b87f-d443-4d17-900f-e699cbd2198c.png)

## Expected Behaviour after application is approved. 
Same as above, just adding the warning message to the modal that already exists when uploading a new ethics letter. 

1. If they upload a file that doesn't already exist in the uploads, this modal will still show:
https://zpl.io/blOm11X

2. If they upload a file with the same name that already exists in the file table of uploads, 
- [ ] show the warning in that modal: https://zpl.io/V4nZl5Q
![image](https://user-images.githubusercontent.com/18424138/131388207-7d007512-3553-44fb-b11b-697620d3921c.png)

**Comment by rosibaj** [comment]
location: 
![image](https://user-images.githubusercontent.com/15824252/134531338-f3849018-a55b-4061-a424-24aabf9148cd.png)

**Comment by ciaranschutte** [comment]
I see https://github.com/icgc-argo/dac-api/issues/163 was closed but do we want backend to only return valid file?

**Comment by kcullion** [comment]
@ciaranschutte 
Sorry if the ticket wasn't clear, but the idea was to just warn them that they are uploading an ethics letter with the same name as the one that's already uploaded. And if they agree, it will replace the old one with the same name. I see it adding both references to the same named pdf.
![image](https://user-images.githubusercontent.com/18424138/137972119-f536d16f-c795-4a54-93a0-a68b16c55f37.png)
![image](https://user-images.githubusercontent.com/18424138/137972217-9b7e9ccb-8fd0-4a76-91b8-c9c925a2dacf.png)

**Comment by kcullion** [comment]
tested in staging and this is working
