### ISSUE TITLE
[Data Hookup + UI] Set up toasts

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#414]
Once infrastructure is ready: https://github.com/icgc-argo/dac-ui/issues/27
Note: these should behave like the ones on Platform, where they are dismissible but also disappear after a short time.

## Success toasts:
- [ ] After an application is `APPROVED`, and the applicant adds a new collaborator, show this toast: https://zpl.io/25medXQ
![image](https://user-images.githubusercontent.com/18424138/131911783-9a303c05-917e-4c13-94f4-68c2b76c5b44.png)

- [ ] After an application is `APPROVED`, and the applicant removes a collaborator, show this toast: https://zpl.io/aXqGg78
![image](https://user-images.githubusercontent.com/18424138/132364970-291613a6-3c58-44a7-b27b-4150f0bbe27b.png)

- [ ] After an application is `APPROVED`, and the applicant uploads a new ethics letter, show this toast: https://zpl.io/25medmr
![image](https://user-images.githubusercontent.com/18424138/131912598-5ac1c230-fe27-4994-8d72-231c67115de1.png)

@rosibaj for these first three, I think we just need to show them when an application is approved because that's when an email gets sent out. Do you think we should also do the general toast (i.e. just the titles of these ones) for before an application is approved (similar to the next toast for closed before approval)?

- [ ] When an application is closed before `APPROVED`, so the user clicks on this confirmation button: https://zpl.io/2Gqj8xd
Show the following toast: https://zpl.io/bAKRgMn
![image](https://user-images.githubusercontent.com/18424138/131910681-539edab4-2ac1-4f60-9cb0-36293b601529.png)

- [ ] When the application is closed after `APPROVED`, so the user (applicant or DACO admin) clicks on this confirmation button: https://zpl.io/V1AxxQJ
Show this toast: https://zpl.io/V4G6OG8
![image](https://user-images.githubusercontent.com/18424138/131910860-0e9af07c-afe5-4c3f-b78f-817e3306026f.png)

## Failure toast
- [ ] If something goes wrong with a user action and they should try again, show this toast: https://zpl.io/boEYORk
![image](https://user-images.githubusercontent.com/18424138/131913512-54e1d663-cad8-4e67-860a-5130318b58c1.png)

**Comment by ciaranschutte** [comment]
@kcullion for the error toast... do you mean any user action across the entire project?

**Comment by kcullion** [comment]
@ciaranschutte I guess maybe if an error occurred at any point when logged in, your error page shows right? I'm not sure what other types of errors could occur - do you know?

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj my thoughts...
So the `error` something went wrong generic page should only be used if user navigates somewhere they shouldn't

This error toast should pop up for any user interaction ie. upload, adding, deleting, modifying. Pretty much every case that isn't navigation.

Does this sound ok ?

**Comment by kcullion** [comment]
@ciaranschutte we already have errors on upload - like  what you did with the file is too large. 

Do you mean then, if there's an unknown error when the user does any action then this toast will pop up? i.e. we don't have to identify every scenario where they could get a user error?

**Comment by kcullion** [comment]
As discussed with @rosibaj and @ciaranschutte  on slack, if we have an API call that fails due to timeout, network failure, etc, after a click or a save id - then show the error toast

**Comment by kcullion** [comment]
Tested in QA and confirmed that I just get the "Closed after approval" banner and not the toast now. Thanks @ciaranschutte !

**Comment by kcullion** [comment]
toasts are working in staging
