### ISSUE TITLE
[UI] Dashboard Card: sign and submit on revisions requested application

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#440]
When an application moves from draft to sign and submit state, but is also flagged as "revisions requested", **please keep the red Status message the same that is on the Draft**
![image](https://user-images.githubusercontent.com/18424138/134212876-dadeca79-8904-4676-b342-aa3692556708.png)

Right now I see it goes back to the original status sentence:
![image](https://user-images.githubusercontent.com/18424138/134213119-c835b9be-33e4-41fb-9a5c-a92f3055fd10.png)

on this application that is in revisions requested 
![image](https://user-images.githubusercontent.com/18424138/134213273-d12d9585-2f60-4b17-987c-404d295158ab.png)

**Comment by samrichca** [comment]
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/6b5dc623-9b6b-4c2c-835c-88ab91241aff)

**Comment by samrichca** [comment]
API dependency: 0.46.0

**Comment by kcullion** [comment]
tested in QA and I see this fixed now. Thanks @samrichca !

**Comment by kcullion** [comment]
Tested in staging, looks good!
