### ISSUE TITLE
[Content Update] Application Terms

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#441]
Please update the bullet point list in the first section to this

- be an independent researcher affiliated with a legal entity (e.g. university professor, researcher in a private company, independent researchers able to apply for federal research grants, etc.)
- have an institutional representative at your institution
- have a scientific abstract and lay summary outlining the desired use of the ICGC Controlled Data
- have at least 3 qualifying publications of which you were an author/co-author
- include an ethics letter, if ethics approval for use of ICGC Controlled Data is required in your country/region

![image](https://user-images.githubusercontent.com/18424138/134220329-a0c98187-5bb0-471c-8db9-f57320f6e593.png)

**Comment by ciaranschutte** [comment]
have at least 3 qualifying publications of which you were an author/co-author
@kcullion should this be 
            have at least 3 qualifying publications of which you are an author/co-author

**Comment by kcullion** [comment]
@ciaranschutte I see what you mean here...but just checked the policy document they sent us and they said "were" instead of "are" so let's leave it so it's consistent. Thanks!

**Comment by kcullion** [comment]
looks great, thanks @ciaranschutte !

**Comment by kcullion** [comment]
this change is reflected in staging
