### ISSUE TITLE
[UI] Feedback for close tickets

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#442]
## Closing Pre-Approval (so when application is in states: `DRAFT`, `SIGN AND SUBMIT`, `REVISIONS REQUESTED`)

- [ ] For the close modal, we need to make this part dynamic to pull in the application number and correct institution name
![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/7ef5726b-78e9-461a-a2f0-48a00d2e3251)

- [x] we don't need to add the red expired date copy (on application or dashboard) when the application is closed pre-approval - so remove this line altogether in these cases
![image](https://user-images.githubusercontent.com/18424138/134225399-e452ca69-e017-4484-89ea-a18dc668d90b.png)

- [x] Same with dashboard card, remove the access expired part
![image](https://user-images.githubusercontent.com/18424138/134225799-a6d3e1aa-dd4b-4df6-9c24-d09b05626bf3.png)

## Closing POST-Approval

- [x] For the close modal, we need to make this part dynamic to pull in the application number and correct institution name
![image](https://user-images.githubusercontent.com/18424138/134229368-068e1fe4-cb7b-4f13-abea-72e2559e7421.png)

- [x] dashboard card: when closing an approved application, the dashboard card should have the red access expired message in top right 
![image](https://user-images.githubusercontent.com/18424138/134230132-15f07e0e-13a4-456f-86f5-7679a846d5a7.png)

**Comment by kcullion** [comment]
@ciaranschutte I think you may have just missed making the primary affiliation dynamic in both modals.
Otherwise this works great!

![image](https://user-images.githubusercontent.com/18424138/134402562-2495b300-3c4d-40e1-a560-fa38af46fcab.png)
![image](https://user-images.githubusercontent.com/18424138/134403060-21b0b66d-9b45-4324-8c73-c9c3ff817405.png)

**Comment by rosibaj** [comment]
@ciaranschutte is this in dev now?

**Comment by kcullion** [comment]
checked in QA and both modals show the dynamic primary affiliation. 
well done @ciaranschutte !

**Comment by kcullion** [comment]
this all works in staging
