### ISSUE TITLE
Header dashboard label change depending on user role

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#47]
- [x] For the applicant, the header label should be "My Applications"
![image](https://user-images.githubusercontent.com/18424138/119519708-a6945a00-bd47-11eb-86db-0ef0b357d826.png)

- [x] For DACO admin, the header label should be "Manage Applications"

![image](https://user-images.githubusercontent.com/18424138/119519614-941a2080-bd47-11eb-8543-e126b33315bc.png)

**Comment by anncatton** [comment]
Will update to ego-token-utils to have a daco admin role check

**Comment by rosibaj** [comment]
looks good thank you @anncatton !

**Comment by rosibaj** [comment]
tested may 31 - logged in as 2 different users and say the change in the header.
