### ISSUE TITLE
[UI] Add Annual Attestation column to admin management table

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#473]
Add this column to the table which marks if an application has an annual attestation submitted or not. 

- [x] if `attestedAtUtc` has a value, the column says `YES`. Don't need to check other values here
- [x] if (1) is false (`attestedAtUtc` is null or undefined), check if `isAttestable` is true. If yes, the column says NO
- [x] otherwise, `isAttestable` would be false and the column would be blank
- [x] Add `PAUSED` state to the `states` query parameter in the admin table query to retrieve these from the api

These fields will be added in [dac-api 240](https://github.com/icgc-argo/dac-api/issues/240)
![image](https://user-images.githubusercontent.com/18424138/135512607-cbc6fe21-deed-417b-9877-16e7064c3b3c.png)

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
