### ISSUE TITLE
[Data Hookup]: Create Application

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#48]
## Goal
To have the applicant click the "Create an Application" button and link to a blank draft application form with a unique id.

## Endpoint to use
https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/post_applications_

## Expected Outcomes
- [x] Applicant can click create application button from the user dashboard
![image](https://user-images.githubusercontent.com/15824252/120039338-bd021600-bfd2-11eb-9a4e-0e5cdad4bcbf.png)
- [x] When clicked, a new application is created in state DRAFT
- [x] When the application is created, the user is redirected to the newly created application.

**Comment by rosibaj** [comment]
@kcullion there are 2 loads; the redirect to the page then the page itself loading all the right information.  #51 is about all the application content being loaded correctly which is not in scope of this ticket.

**Comment by rosibaj** [comment]
@ciaranschutte this one looks great, thank you! 
- tested and was able to create programs several times
- saw the program number increment as i created new applications, 
- was redirected to the application on create. 
![image](https://user-images.githubusercontent.com/15824252/122467943-1681b300-cf89-11eb-8dcc-a148c55f7ce9.png)
