### ISSUE TITLE
[UI] Dashboard card for attestation required (45 days prior to 1 year mark)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#485]
Build the dashboard card for when the application requires attestation (which will change 45 days prior to the 1 year of access mark)

Zeplin: https://zpl.io/bloeKQ1

- [x] Check if `attestedAtUtc` is NOT present, and `isAttestable` is TRUE, if so, show the pausing card for the application:
- [x] 1. Change expiry date to Access Pausing alert date
- [x] 2. New red status sentence
- [x] 3. Button still links to application, but the label changes to "Complete Attestation" and icon changes to "Calendar"

![image](https://user-images.githubusercontent.com/18424138/136271152-cb23a977-796f-4dbc-865d-4297abf3a0d4.png)

**Comment by kcullion** [comment]
@daniel-cy-lu here is the related API ticket: https://github.com/icgc-argo/dac-api/issues/236

**Comment by anncatton** [comment]
Status text was updated to `An annual attestation is required for this application. Attestation must be completed by <date> or access for this project team will be paused.`

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
