### ISSUE TITLE
[UI] Application when access is paused because attestation hasn’t been completed

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#486]
## Goal
To transition the application into PAUSED state when the attestation hasn’t been completed:

## Expected Outcomes

Zeplin: https://zpl.io/bloeKXP
- [x] Check the API for application that are in PAUSED state 
- [x] 1. Header change: show Paused date in red
- [x] 2. Header change: show the new progress bar with APPROVED changed to PAUSED
- [x] 3. Lock application for edits
- [x] Keep the banner that was built in https://github.com/icgc-argo/dac-ui/issues/484 

![image](https://user-images.githubusercontent.com/18424138/140531765-66fe69dd-f5bd-4817-bf16-6a84957372ea.png)

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
