### ISSUE TITLE
[Content and UI] Section D Lay Summary Updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#488]
## Updates

- [x] 1. Add the "How to Write a Lay Summary" button, link (open in new tab) https://docs.icgc-argo.org/docs/data-access/daco/lay-summary-guide
- [x] 2. Revise the field label to be `Lay Summary (min. 100 words, max. 250 words)`
- [x] 3. Revise the instructions to reflect the mock (zeplin is crashing for me right now so see content below)
- [x] 4. First link in instructions goes to the url stated, second link is same as button link to docs site- TBD (open in new tab)
- [x] 5. Change the form validation to work with max 250 words instead of 200 words from a UI standpoint. Related API ticket here: https://github.com/icgc-argo/dac-api/issues/295 

![image](https://user-images.githubusercontent.com/18424138/155224729-4be5ff2e-0bee-4b3e-bb83-c67d688b33bb.png)

`Content:`
Provide a summary of your project targeted towards the general public. 
**When writing your lay summary:**
•  Develop the language in your lay summary as if you are describing the project to someone outside your field.
•  Define any technical terms used. 
•  We strongly recommend you use an online readability tool such as www.readabilityformulas.com to assess the reading     grade of your text. The reading grade level to be aimed at for the lay summaries is grade 8 or 9.
•  Explain in plain language why you are asking the research question, what you expect to find out and how you plan to use the  findings. 
•  Consider the 3 key elements when developing your lay summary: **structure and content, readability, and language guide**.  Finding it challenging? Read our lay summary guide, which includes before and after examples of real lay summaries. 

## Reminders FOR KIM
- [ ] update faq docs with url
- [x] add lay summary guide to docs

**Comment by anncatton** [comment]
@kcullion fyi i put the argo docs url in as a placeholder for the lay summary guide, and left a todo note to update it once we have the correct url

**Comment by kcullion** [comment]
@anncatton this will be the link for the lay summary guide https://docs.icgc-argo.org/docs/data-access/daco/lay-summary-guide

**Comment by kcullion** [comment]
Reviewed in QA. This looks great @anncatton thanks!

**Comment by kcullion** [comment]
I see the change as expected on staging
