### ISSUE TITLE
[Data Hookup]:Load Application Data + Sidebar States for each section/state of application

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#49]
## Goal
- For each application section, the applicant can see the correct data in their application, as well as the correct state of that secion on the left nav bar
- Note: the user still cannot use the FE to save data. 

## Endpoint to use
- this relies on the PATCH Applications/id 

## Expected Outcomes
All behaviours outlined on the wiki are working, which include:
- [x] Just clicking through the sections and not interacting with the forms will not save anything, and no icons will be shown in the table of contents
- [x] Table of contents shows the green checkmark when a section is valid and complete
- [x] Table of contents shows the red ! Icon when a section is incomplete or has saved errors
- [x] Sign and Submit section is disabled until all of the other sections are complete
- [x] FOR TESTING PURPOSES:  logging out and logging back in should show the same saved state (which is connected to this ticket https://github.com/icgc-argo/dac-ui/issues/51)
- [x] A local error on a field (red text underneath) only gets saved to that section when a user has filled out that field incorrectly, or filled it out incorrectly and erased the value leaving it blank. Tabbing through the field will show the error but not get saved unless the applicant fills it in incorrectly.

Note: saving and editing for collaborators is broken out into this ticket; https://github.com/icgc-argo/dac-ui/issues/52
And ethics in this ticket; https://github.com/icgc-argo/dac-ui/issues/58

**Comment by rosibaj** [comment]
- does not include collaborators, etthics just set to no for now), and sign and submit.

**Comment by caravinci** [comment]
Changes in this ticket also correct some earlier implementation issues
- positioning of the Application form's Loader
- Application header's last update minutes would display incorrectly when < 10 (e.g. `4:3` vs `4:03`)
- replaces the hook used in the header, to use the same `useApplicationApi` as everywhere else in this section.

**Comment by kcullion** [comment]
Working great @caravinci !

Regarding the sidebar - there may be some gaps in the TOC behaviour but we have or will make tickets as we see them (eg. this one still needs to be put into a sprint: https://github.com/icgc-argo/dac-ui/issues/96)

There are some fields that aren't coming through on the application when I submit through postman. I will list them on this ticket: https://github.com/icgc-argo/dac-ui/issues/168

**Comment by rosibaj** [comment]
lgtm for now - thank you @caravinci for the initial hookup.  Moving this to awaiting release.
