### ISSUE TITLE
[UI] Dashboard card for access paused

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#490]
Build the dashboard card for when access has been paused. 

Zeplin: https://zpl.io/bzOODez

- [x]  Check for applications in PAUSED state
- [x] 1. Change expiry date to Access Paused alert date
- [x] 2. New red status sentence
- [x] 3. Button still links to application, but the label is "Complete Attestation"
- [x] 4. Progress bar shows PAUSED state in red color
- [x] set `PAUSED` as an allowed state for the applicant's list. with the api changes from dac-api 238 this page will error with an `Illegal State` warning
![image](https://user-images.githubusercontent.com/18424138/136455253-5f645444-ed71-4d8d-b6dd-0e83a1b1ea00.png)

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
