### ISSUE TITLE
[UI] Application when the applicant attests

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#491]
## Goal
To transition the application back into the APPROVED state when the attestation is completed.

Endpoint: https://github.com/icgc-argo/dac-api/issues/240

## Expected Outcomes

Zeplin: https://zpl.io/anvvWWr
- [x] An attested application will return a field `attestedAtUtc`, the value will be a date string. If attestation hasn't been completed yet, the field will not be present in the response
- [x] When the user presses the "I attest to the above terms" button in the banner built in this ticket: https://app.zenhub.com/workspaces/daco-61ba4137548d07001305d73e/issues/icgc-argo/dac-ui/484
![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/c487e262-fe8b-4ed7-9273-ae58e08a0581)
The application transitions to:
- [x] 1. Header change: transforms back to the approved version of the header
- [x] 2. The application goes back to the approved version (with correct sections unlocked).
- [x] 3 Show the success banner. This banner should be dismissible and should disappear if the user navigates away from the application and comes back (like the success banner that displays when an applicant submits an application).

![image](https://user-images.githubusercontent.com/18424138/136458162-cbc51200-d083-4629-990e-ac29c42613f3.png)

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
