### ISSUE TITLE
[UI]: Homepage Layout

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#5]
**Goal:** The layout and style for the homepage: zeplin: https://zpl.io/aMoJPZR 

- [x] 1. Intro blurb (Apply for Access button will link to the modal built in https://github.com/icgc-argo/dac-ui/issues/7)
- [x] 2.What will you get access for?.  Please link the `ARGO logo` and `ICGC ARGO` text link to https://platform.icgc-argo.org/ (open in a new window) and the `ICGC logo` and `ICGC 25K Data Portal` links to https://dcc.icgc.org/ (open in a new window). The `PCAWG` text links to https://dcc.icgc.org/pcawg (open in a new window)
- [x] 3. Overview (bottom `faqs` link TBD)
- [x] 4. Application Process (`eligible project team` link TBD)

Note: the banner image is still being decided on. Let me know if you need a placeholder image

![image](https://user-images.githubusercontent.com/18424138/117181686-822a0b00-ada3-11eb-8e7d-c240446dcd0d.png)

**Comment by rosibaj** [comment]
@samrichca this look great; thank you very much!
