### ISSUE TITLE
[Data Hookup]: Progress bar on dashboard and application header

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#50]
## Goal
For each application state make sure the progress bar is reflected correctly on the application itself and dashboard card

## Use Endpoint
GET endpoint 

## Expected Outcomes
Each of these states are covered
- [ ] DRAFT https://zpl.io/a8ngJGJ
- [ ] SIGN AND SUBMIT https://zpl.io/29mQEYy
- [ ] DACO REVIEW https://zpl.io/bo3qGrZ
- [ ] REVISIONS REQUESTED https://zpl.io/Vx3zv5R
- [ ] APPROVED https://zpl.io/2ZMEE7J

**Small access card**

- [x] For approved, show this card when the DACO scope is available in the user JWT. 
![image](https://user-images.githubusercontent.com/18424138/122287731-43699380-cebf-11eb-919e-b529e3430e7d.png)
- [x] For all other states above, show this card
![image](https://user-images.githubusercontent.com/18424138/122287571-14532200-cebf-11eb-9457-90f9357415b7.png)

(note: for revisions requested the mockup says "revisions needed". You can keep it as `revisions requested`. So the above labels are what should be shown in the progress bar UI)

**Comment by ciaranschutte** [comment]
@rosibaj won't have this in before sprint planning. There is a couple af hours work left on this with testing included.

**Comment by rosibaj** [comment]
@ciaranschutte does this include data hookup for the whole card?

**Comment by ciaranschutte** [comment]
@rosibaj yes.

**Comment by ciaranschutte** [comment]
some overlap with the work Sam did. waiting for a PR to be merged to dev to resolve this overlapping.

**Comment by rosibaj** [comment]
lgtm thank you @ciaranschutte

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
