### ISSUE TITLE
[UI] Dashboard card for expired applications

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#505]
## Goal
When an application expires, the applicant will see this on the dashboard card.

## Expected outcomes

- [ ] Check for applications in EXPIRED state show expired card which:
- [ ] 1. The expiry date is red and says "Access expired" 
- [ ] 2. The progress bar shows the expired alert
- [ ] 3. The status message changes and is red 
- [ ] 4. The "Renew Application" is still available

zeplin: https://zpl.io/boEg7Em

![image](https://user-images.githubusercontent.com/18424138/137786277-2539975b-2f81-4fef-9c9c-17758027b44d.png)

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
