### ISSUE TITLE
[UI] Dashboard card for a renewal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#506]
## Goal
When an application is a renewal, the applicant will see the following on the dashboard card.

## Expected outcomes if renewed when NOT EXPIRED
- [ ] Check isRenewal=true and ableToRenew=true, then show the renewal card that has:
- [ ] 1. The expiry date changes to red with a "!" icon and says "Access expiring: date"
- [ ] 2. The progress bar shows that the application is in DRAFT again
- [ ] 3. The status message changes and is red 
- [ ] 4. The button that's available is "Edit Application" 
zeplin: https://zpl.io/2G5gM5Y
![image](https://user-images.githubusercontent.com/18424138/137792598-87c01ad0-d6c5-4217-b7cc-c119e0cad0ac.png)

## Expected outcomes if renewed when IS EXPIRED
Same as above except:
- [ ]  5. The expiry date is red and says "Access expired:Date" 
Zeplin: https://zpl.io/bloRBB5
![image](https://user-images.githubusercontent.com/18424138/137792899-2fc3d175-e4cf-40fe-b547-cf1db7af026c.png)

## For Testing 
- [ ] Make sure this covers draft and sign and submit states this time

**Comment by patrickdsantos** [comment]
If the application is renewed a new application with a different name is generated. It will look like this: 
![Screen Shot 2023-01-31 at 11.34.54 AM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/55fbf32f-929b-444e-8a04-902b0f5c6ceb)

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
