### ISSUE TITLE
[UI] Application in EXPIRED state 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#507]
## Goal
If the applicant doesn't renew an application before the expiry date, the application should transition into EXPIRED state.

API ticket: https://github.com/icgc-argo/dac-api/issues/252

## Expected Outcomes
(A lot of this may be automatic from the API)
- [ ] Check for applications that are in EXPIRED state 
- [ ] 1. Header shows "Expired: date" in red
- [ ] 2. Header progress bar shows expired state
- [ ] 3. Renew button is available still 
- [ ] 4. All application sections are locked 

Zeplin: https://zpl.io/V0NnY99
![image](https://user-images.githubusercontent.com/18424138/137794913-e4994504-2edd-45b9-bbd7-c49d80132fdb.png)

**Comment by patrickdsantos** [comment]
If the application has been renewed, the original app will look like this: https://zpl.io/wqAYByn

![ExpiredState.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/3b1eb170-35f6-40eb-b8a4-927c8e4e4d37)

- Renewal button is removed 
- Info message with link to application renewal

**Comment by anncatton** [comment]
Released in production, not able to verify. Will open a new ticket if issues arise
