### ISSUE TITLE
[UI + Data Hookup] Hook up Renew button and transition to Renewal mode

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#508]
## Goal
When the applicant clicks the "Renew" button from the dashboard or application, a new application will be created, with copied sections from the original application

Renew button for dashboard card will be implemented in #504 

API ticket: https://github.com/icgc-argo/dac-api/issues/364

## Expected Outcomes

- [ ] When the applicant clicks on the "Renew Application" button from the dashboard card OR the application header, it should take them to the newly created renewal app, landing on the first section

**Renewal Application**
Zeplin: https://zpl.io/VYMm91L
- [ ] Use `/renew` endpoint from https://github.com/icgc-argo/dac-api/issues/364
- [ ] 1. Header: Add “Renewal Application” flag
- [ ] 2. Renew button disappears
- [ ] 3. Progress bar shows the draft state now
- [ ] 4. Add instruction banner to top of application (not dismissible)

## For Testing
- [ ] verify the application has copied all relevant section data
- [ ] The last 2 agreement sections are cleared and are mandatory again.
- [ ] The sign and submit section is cleared
- [ ] The pdf download goes back to the usual DRAFT and FINALIZED version

![image](https://user-images.githubusercontent.com/18424138/137796762-a0ec4e8f-9866-4edc-99f7-568ef6b2f053.png)

**Comment by patrickdsantos** [comment]
The original application no longer transitions into a renewal. When an expiring application is renewed, a brand new application is created. This is the page: https://zpl.io/8lmKzQd
![Renewal.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/b90485ca-5169-4118-b841-43dea512744b)

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
