### ISSUE TITLE
[Data Hookup] Load Application and correct metadata (header)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#51]
## Goal
An application loads from the dashboard links or admin dashboard table in the correct state with the correct header metadata.

- included implementing the standard Data Provider (also in progress with @samrichca to be discussed)

## Endpoint to use
- powered by this endpoint: https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/get_applications__id_ 

## Expected Outcomes
- [x] The correct application loads (landing on the introduction/application terms section): 
1. Clicking an application dashboard card
2. Clicking an application from the admin table dashboard
3. a direct URL is visited and the user has permission to load it (eg. from an email)

- [x] The header information has the expected information (some depends on filling out section A)
1. Application ID
2. Show the Creation date and last updated date/time
3. When applicant fills out the application name - show title, first name, last name in header bar
3. When applicant fills out primary affiliation in section A, show that with the applicant info too

![image](https://user-images.githubusercontent.com/18424138/120361779-43bb3980-c2d8-11eb-94b2-a1cba03a5d20.png)

- [x] Link "My Applications" back to the user's dashboard 
![image](https://user-images.githubusercontent.com/18424138/122234589-fec40500-ce8a-11eb-873b-a92c4d04aed0.png)

Progress bar data hookup is covered here: https://github.com/icgc-argo/dac-ui/issues/50

**Comment by ciaranschutte** [comment]
as discussed in standup reassigning to @caravinci

**Comment by caravinci** [comment]
Extending scope a smidge to include handling of this:
> https://github.com/icgc-argo/dac-api/issues/34#issuecomment-863479445
> ![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/cbf824b1-6ec3-41db-af38-0201121be83d)

**Comment by rosibaj** [comment]
lgtm as a start.  thank you @caravinci!
