### ISSUE TITLE
[UI] Submitting a renewal application

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#514]
## Goal
When the applicant clicks the "Submit Application" for a renewal, the application should lock, and the applicant will see a success banner.

API ticket: not sure if one was needed.

## Expected Outcomes
Zeplin: https://zpl.io/VqMyvG5
- [ ] 1. Header: Keep the “Renewal Application” flag
- [ ] 2. Add success banner - similar to the original success banner on submission, just with the added "renewal" word.
![image](https://user-images.githubusercontent.com/18424138/138512796-8ad953d7-0224-4787-8da1-1697e707d45a.png)

## For Testing
- [ ] Verify the application is locked 
- [ ] The pdf download goes back to the usual SIGNED version
- [ ] Test when approving this application, the Renewal Application flag stays in the header.

**Comment by patrickdsantos** [comment]
With the new user flow, when the user renews an application a new application is created. The original application that is expiring will look like this (after a renewal has been started) : 
- when the original application is about to expire: https://zpl.io/PqQYMAx
- when the original application has already expired: https://zpl.io/wqAYByn

When the renewal has been submitted and approved, the original expired application will look like this: https://zpl.io/wqAYByn

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
