### ISSUE TITLE
[UI] Admin table - add Type column

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#515]
For the admin management table

- [ ] Display the Type column for New/Renewal
![image](https://user-images.githubusercontent.com/18424138/138513295-fb23d704-8e3d-4294-9585-84f30b58738e.png)

## For testing

- [ ] When expired after 2 years, the state in the table changes to expired and the date is red
- [ ] Approved renewals will be the same as an approved new application: the attestation column will be empty and the admin will need to upload a new PDF

**Comment by b-f-chan** [comment]
@anncatton - Testing feedback, as agreed, let's move Status column before Type, as it is more useful.  And since small fix, let's include in this next release.

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
