### ISSUE TITLE
[UI] Dashboard card expired forever: non renewable 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#516]
## Goal
When an application passes the renewal window (over 90 days after expiry), show this dashboard card.

## Expected outcomes 
zeplin: https://zpl.io/VO30dkQ
- [ ] Check ableToRenew = false and state = EXPIRED, show expired forever card:
- [ ] 1. The progress bar shows all grey and 'X" with expired being the last label
- [ ] 2. Show new status message
- [ ] 3. Show "view application" button 
- [ ] 4. Show the same callout for the final report that was implemented here: https://github.com/icgc-argo/dac-ui/issues/463
- [ ] 5. TESTING: make sure expired date is showing in red still 

![image](https://user-images.githubusercontent.com/18424138/138515253-b5b7160c-2ffd-4ee1-8f94-a0660b8c9d18.png)

**Comment by patrickdsantos** [comment]
The above applies if the renewal has expired before submission. If the original application expires without renewal the status bar will look like this: 

![Screen Shot 2023-01-31 at 2.01.10 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/7278bcdd-e955-4d97-816a-d31b434e870a)
