### ISSUE TITLE
[Data Hookup]: Add, Edit, Remove Collaborators

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#52]
## Goal
To be able to add, edit and remove Collaborators to the application, with the correct table of content states shown

## Endpoint to use
https://github.com/icgc-argo/dac-api/issues/9
PATCH for Edit: https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/patch_applications__id__collaborators__collaboratorId_

## Expected outcomes

- [x] Connect the save for the collaborator modal - so only when an applicant fills out this modal form correctly will they be able to save the collaborator to the application
- [x] When a collaborator is added, show the correct metadata about them in the Collaborator table here: https://zpl.io/a7PP8DM
- [x] Connect the edit (pencil) icon. When clicked:
1. Show the modal with the saved field values for that collaborator. 
2. Change the purple button label from "ADD COLLABORATOR" to "SAVE COLLABORATOR" 
3. If the applicant removes a value that is required - disable the "SAVE COLLABORATOR" button until they fill out the form correctly.

- [x] Connect the remove (trashcan) icon. When clicked:
1. Show the remove collaborator confirmation modal Zeplin: https://zpl.io/agmGZXQ
![image](https://user-images.githubusercontent.com/18424138/120363670-68181580-c2da-11eb-8f3b-2ad717391fd2.png)

2. when the applicant clicks "Remove collaborator", close the modal, remove the collaborator from the application and from the collaborator table. (success toast will be done in this ticket: https://github.com/icgc-argo/dac-ui/issues/27)

- [ ] FOR TESTING PURPOSES. Make sure this backend feature works in the UI: 
This section gets checked off in the table of contents when: 
1. A collaborator is added
2. No collaborators are added, and the last section is completed, then check this section off and enable the Sign and Submit section. (wondering if this should be in https://github.com/icgc-argo/dac-ui/issues/59)

**Comment by caravinci** [comment]
Implementation completed with the following caveats:
- Just realised the button was supposed to change to `Save Collaborator` when editing an existing collaborator, as **clearly stated in the ticket**; but instead I've made it `Edit Collaborator` by mistake. I will amend this in a subsequent PR (change already made in my local).
- If all the fields are filled correctly (and currently most of the validation happening while a user types does seem to work, so this shouldn't be a huge issue), the button to save will be enabled, and a new collaborator will be created. If there are any UI validation errors, the button should remain disabled (WIP). I believe this is improvement overlap from #214.
- However, when creating a new collaborator, if the API responds with a BE validation error (e.g. primary affiliation doesn't match) the modal won't show any errors, and the user won't be able to save the collaborator. This functionality will be correctly addressed in ticket #142.

**Comment by kcullion** [comment]
@caravinci I added your first two points to the feedback ticket https://github.com/icgc-argo/dac-ui/issues/214
(and clarified the first point)
Please move on to the other validation tickets and I will let you know if any of this feedback is urgent for the soft launch

**Comment by caravinci** [comment]
Thank you 🙏 will comply!

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
