### ISSUE TITLE
(bug) Deleting publication URLs

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/dac-ui#530]
1. Add a publication URL field
2. Type in a URL
3. Delete the field - it will probably keep the field but remove the text
4. Delete the field again - it should delete the field this time

I think this is happening because publication URLs are stored in a simple string of arrays rather than in an object with indices, but I'd be careful of potential side effects when changing the data structure.

**Comment by anncatton** [comment]
@kcullion I may have fixed this behaviour in #439

**Comment by anncatton** [comment]
Fixed in #439 , closing
