### ISSUE TITLE
Implement a maintenance page for release

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#539]
Implement this page, but within the DACO website:
https://platform-ui.qa.argo.cancercollaboratory.org/maintenance

- [x] Hide the top "apply for access" and login buttons
- [x] Hide the footer links to platform.icgc-argo.org

![image](https://user-images.githubusercontent.com/18424138/155809170-51341664-dfc4-4693-946a-ec7e9a7d489f.png)

**Comment by akachru-github** [comment]
Let's confirm how platform does this. 
Confirm with IT how to host this in production. Deadman switch would be nice to have, but minimally we would require ability to manually switch over to this from the LB.

**Comment by akachru-github** [comment]
IT ticket: https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-40759

**Comment by kcullion** [comment]
The netlify page looks good to me! I'll leave this in QA for Atul to review Ann's question
