### ISSUE TITLE
Build a static page for daco.icgc.org to redirect to

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#540]
OICR IT to implement a static html page that will be posted on daco.icgc.org for public users to read before they click to redirect to the new daco.icgc-argo.org.

Content is not confirmed yet, but we can build this page for now: https://zpl.io/5EkPZE8

![image](https://user-images.githubusercontent.com/18424138/156597335-cb0c2129-ad28-4d36-be7b-0079111e0e5e.png)

Page to live on daco.icgc-argo.org/new-website-notice

**Comment by kcullion** [comment]
@anncatton just a quick picky update from me - just to add more space in between the "chunks of headline/paragraph"

![image](https://user-images.githubusercontent.com/18424138/158241474-d0fe053f-68ae-4788-83c3-5f88f51240b9.png)

**Comment by akachru-github** [comment]
@kcullion to ping Amber on updating content.
