### ISSUE TITLE
[UI]: Administrator management actions bar and DACO Review application state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#55]
**Goal:** Add the DACO Admin actions bar to the top of the application page, and load the application in DACO REVIEW state with all sections locked.

**NOTE: Ignore the Customize Expiry date field for now. To be built after MVP**

## Expected Outcomes
- [ ] When the application loads for the DACO Admin role, they have an extra actions bar with three buttons
* note done in #61 

![image](https://user-images.githubusercontent.com/18424138/120369551-6bfb6600-c2e1-11eb-9aa4-349dc268b989.png)

**Comment by rosibaj** [comment]
closing as this is done
