### ISSUE TITLE
[UI] Add a minimum word count to each scientific abstract section in section D

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#570]
- [x] In section D, for all scientific abstract fields ( the `Background`, `Aims`, `Use of Data and Methodology`) change the brackets to validate like the lay summary field except use min words: 100 and max words: 200

Request from Amber:

`Section D: we may have discussed this in the past- can we add a minimum word number to each scientific abstract section? I was able to just write 2 letters in a few. Although I doubt many will realistically do this it might weed out those few who will only want to write a few lines. `

**Comment by ciaranschutte** [comment]
ok in dev

**Comment by kcullion** [comment]
Tested in QA. This is working as expected. Thanks @ciaranschutte !
