### ISSUE TITLE
Remove General terms checkbox from first section 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/dac-ui#571]
no longer needed from Amber's feedback
![image (93)](https://user-images.githubusercontent.com/18424138/162977850-4fa6ab75-0b51-4b83-b0a9-136e2da184f0.png)

## Expected outcomes
- [ ] The checkbox is removed from the first section
- [ ] The first section doesn't count towards application completion
- [ ] Change the title from "Application Terms" to "Introduction"
- [ ] The section remains in the pdf
- [ ] It's ok if this section does not show a completed checkmark icon

**Comment by kcullion** [comment]
Tested in QA. Working as expected. Thanks @anncatton !
