### ISSUE TITLE
Ethics section V3 - POST APPROVAL states (ui + data hookup)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#58]
## Goal
This ticket also includes the Ethics section for after the application is approved. 

## Endpoint to use
https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/post_applications__id__assets_url

## Expected Outcomes after Approval
- [x] 1) If Applicant has selected option 1 (no ethics letter required),  then lock this section shoudl be locked with the grey status in left bar.  No actionns can be taken at this point. 
- [x] 2) If Applicant choses option 2 (required ethics letter) then a few things apply: 
  - this section is unlocked for edits, 
  - option 1 is disabled
  - remove the actions column from the table.  The applicant cannot delete files from this section 
  - the UPLOAD A FILE button should still be enabled. 
![image](https://user-images.githubusercontent.com/15824252/122591573-22c14b00-d031-11eb-96af-8a2f6797e1e1.png)
- [x] 3) Clicking "Upload a file button triggers the browser file upload window to choose a pdf/doc/docx file, with the validations that were already coded. When the user chooses a file and uploads, implement a new confirmation modal for when they upload a new letter. This triggers the email being sent to DACO admin (https://github.com/icgc-argo/dac-ui/issues/73), so we want them to confirm this action. **MOCKUP: https://zpl.io/blOm11X**
![image](https://user-images.githubusercontent.com/18424138/120700686-f24dae80-c47f-11eb-99ce-a4934e46447b.png)

**Comment by samrichca** [comment]
scope note: fixed the ethics letter count & pluralization while working on the table

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/2e0ad65d-db02-4d12-8d9d-855e4bfeb29a)

**Comment by samrichca** [comment]
scope note 2: ethics letters aren't showing up in the table on initial page load or refresh, only when i upload a new letter

**Comment by rosibaj** [comment]
tested Jul 30, 2021 
- was able to upload 2 ethics letters 
- counts are right at the top of the table 
- was able to see 2 letters when clicking away from ethics section and clicking back, and on refresh, 
- saw the correct ethics letters in locked state as well, and on refresh

**Comment by rosibaj** [comment]
thank you @samrichca - everything looks great with the ethics letter addition now!
