### ISSUE TITLE
[Data Hookup + UI] Sign and Submit section

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#59]
**Goal:** Hookup the sign and submit section

### UI Updates

- [x] update link color; 
![image](https://user-images.githubusercontent.com/15824252/125519705-9132aede-6d2b-4348-a914-64c4c0aafc0e.png)
- [x] Open these links as a new tab: 
![image](https://user-images.githubusercontent.com/15824252/125519795-fd5ef1db-d720-4050-b7ff-b2919dbf5baa.png)
- [ ] display issue on the PDF name when loading the sign & submit section. 
![image](https://user-images.githubusercontent.com/15824252/125520276-334c78da-d8fa-47bc-bff7-9a93f6faba0a.png)
- [x] When the Submit application button is clicked, show the confirmation modal: https://zpl.io/b6AlPJy

### Data Hookup Updates
- [x] The `finalized` pdf button mid test should download the finalized PDF (same as button at top) 
- [x] Connect the `delete` trashcan button on the pdf table 
- [x] Connect the confirmation modal to the submit endpoint: https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/delete_applications__id__assets__type__assetId__assetId_

**Comment by rosibaj** [comment]
@ciaranschutte assigned in planning; @caravinci has an example implantation already to follow.  If you need to review the features before starting just lmK!

**Comment by kcullion** [comment]
@ciaranschutte 
- [ ] when I upload the file in sign and submit, the section gets checked off by I can't see the file reference on the form
![image](https://user-images.githubusercontent.com/18424138/126522369-077421ee-30d6-4469-98a2-71a6890bd0d0.png)

**Comment by rosibaj** [comment]
feedback ticket is comprehensive, moving this code chunk to awaiting release.
