### ISSUE TITLE
Lay summary instructions incorrectly aligned on PDF

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#590]
<img width="750" alt="lay_summary_alignment" src="https://user-images.githubusercontent.com/5624601/165150943-4de693bd-1d38-4a21-b8cb-805187852a0c.png">

**Comment by b-f-chan** [comment]
Confirmed fix in QA, moving to Ready for Staging

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
