### ISSUE TITLE
[Data-Hookup] Generate pdf with applicant data in correct states

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#60]
- always export CURRENT state of the form, in the pdf
- Has draft watermark if in draft state, otherwise no watermark
- test with 1 section downloading the values based on the investigated method. 
- (Not sure where to put this) - for all links in the content of the form, display the url in brackets after that link text within the pdf

UI zeplin links can be found: https://github.com/icgc-argo/dac-ui/issues/64

**Comment by anncatton** [comment]
Initial setup in 0.9.0:

- hookup pdf download to Draft PDF button (button does not reflect app state yet)
pdf will show static text for `Introduction` and `Applicant Information`
- `Introduction` acknowledgement should show correct state from what is latest in the api
- watermark should reflect current app state
- `Applicant Information` has only static text and form data subtitle, no app state yet

Work for the rest of the pdf is continuing and will appear in a later release

**Comment by kcullion** [comment]
thanks @anncatton . Will review more when more sections are in there but for now, let's change the name format to 
`ICGC-DACO-32-20210628.pdf`
