### ISSUE TITLE
Refresh Token feedback after testing dev

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#604]
A place to collect any of the bugs we find while testing Sam's amazing work!

**Comment by samrichca** [comment]
As an admin, when my JWT has been refreshed, if I go to the Sign & Submit section of an application, it sends me to the `/logged-in` page. The app crashes and I get logged out.

**Comment by blabadi** [comment]
Issue: Form fields empty after refresh
steps:
1- fill app section project information
2- move to another section
3- wait for refresh to happen 
4- go back to project info 
section will be empty:
![image](https://user-images.githubusercontent.com/8655252/171902017-4458dabb-e16e-42f5-8890-3f7731b946fc.png)

**Comment by kcullion** [comment]
> Issue: Form fields empty after refresh steps: 1- fill app section project information 2- move to another section 3- wait for refresh to happen 4- go back to project info section is partially empty (text areas): ![image](https://user-images.githubusercontent.com/8655252/171902017-4458dabb-e16e-42f5-8890-3f7731b946fc.png)

I noticed this too - even when I opened an application for revisions..all of the saved text area data was gone when opening the reopened application:
![image](https://user-images.githubusercontent.com/18424138/171945344-44b20cc4-ac05-4251-9af5-093f871b73c3.png)

**Comment by samrichca** [comment]
- When viewing an application, when changing from section A to B, there are several router events and fetch calls.
- Users briefly see a loading screen.
- This doesn't happen when switching between other sections
- Could create a race condition with auth requests and cause the app to crash

**Comment by samrichca** [comment]
When a user opens a modal it should trigger the same auth check as going to a different page or section, downloading/uploading a file, or updating a form.

**Comment by kcullion** [comment]
Also made this ticket for session timeout modal: https://github.com/icgc-argo/dac-ui/issues/605

**Comment by b-f-chan** [comment]
No longer using this implementation/mechanism, closing
