### ISSUE TITLE
Refresh Token: implement the session timed out modal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#605]
- [ ] When user is inactive for a period longer than 3 hours of inactivity (refresh token duration), whatever page they are on, show this modal that warns them they will be logged out due to inactivity. 
- [ ] If they choose "yes, log in", take them to the google login page
- [ ] If they choose, "no" - log them out and take them to homepage

Zeplin: https://zpl.io/VYvrBxe
<img width="647" alt="Screen Shot 2020-06-23 at 2 01 28 PM" src="https://user-images.githubusercontent.com/18424138/85438473-0ee82380-b55a-11ea-8836-0ccac369eb28.png">

Suggested Implementation:
- Set a refresh token timer when the JWT is refreshed, when it expires (due to inactivity) show the modal and overlay 
- when user logs out, remove the time

Question:
-- User gets redirect to the section they were on or the first section ? we already redirect in JWT refresh so it seems possible to do same here

**Comment by b-f-chan** [comment]
Closing for now until Ego has a refresh mechanism, we haven't had any complaints here.  Can reopen later if it's an issue.
