### ISSUE TITLE
Fix missing spaces in PDF terms

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#607]
Some spaces got missed in a couple term points (in the PDF only):

![image.png](https://images.zenhubusercontent.com/5db070c75e806700019cb512/c5b83343-20aa-4198-8e9c-46f0bdad3972)

![image.png](https://images.zenhubusercontent.com/5db070c75e806700019cb512/5f3016c4-7acb-445c-a0c8-2d7abc5988da)

**Comment by kcullion** [comment]
I see this fixed in QA. Thanks @anncatton !

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
