### ISSUE TITLE
Give DACO admin ability to add and delete a collaborator

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/dac-ui#626]
When an application is being reviewed or approved, the daco admin has the option to add or delete a collaborator:
![Screen Shot 2022-08-12 at 10 45 43 AM](https://user-images.githubusercontent.com/8744047/184380272-683554f4-56f3-4216-b4f4-2fd2dd637636.png)

Requesting that the admin have the ability to do so

**Comment by b-f-chan** [comment]
This is already supported, it is a feature requirement, closing
