### ISSUE TITLE
Allow special characters in forms

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#628]
Need to investigate if this is a UI and/or API issue, will update this ticket if necessary.

Applicants are not able to submit form values that have special characters (i.e. an applicant name that contains an accented letter).

**Make sure it works for all Unicode & all languages**

**Comment by b-f-chan** [comment]
May be complex in implementation --> Investigate solution feasibility and complexity

**Comment by b-f-chan** [comment]
Tried reproducing in QA with @anncatton, using Chinese characters, still could not reproduce.  @anncatton and @justincorrigible also tested this with other languages and could not reproduce.  Removing from release and putting in icebox.  Will revisit if needed in future.  In meantime, @b-f-chan will let Judith know the result.
