### ISSUE TITLE
[UI] Request Revisions modal/form

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#63]
## Goal
To build the modal that is triggered when admin clicks the Request Revisions button from https://github.com/icgc-argo/dac-ui/issues/55

Note, the revisions requested email that gets triggered will be built in this epic: https://github.com/icgc-argo/dac-ui/issues/65)

## Endpoint to use
https://github.com/icgc-argo/dac-api/issues/17

### Add the Admin UI Bar
 When the application loads for the DACO Admin role, they have an extra actions bar with three buttons
Zeplin: https://zpl.io/2jq8Z96
![image](https://user-images.githubusercontent.com/15824252/120671469-688de900-c45f-11eb-8ba2-57dd52856858.png)

### Confirmation Modal
- [ ] Build the UI for the Request Revisions confirmation modal as seen: https://zpl.io/VOLWoek
- [ ] 1. Include only the sections of the form, as shown below, that do not just have agreement checkboxes (those will never require revisions)
- [ ] 2. The admin can check off the sections that require revisions and add specific details to be revised. 
- [ ] 3. If the admin, say, checks off a section like Section E:Ethics, then fills in a reason, then unchecked that section - the text area reason should be cleared.  
- [ ] 4. The last "Include general comments in email" item should only be enabled if another section is checked off. i.e. the Admin cannot just send a general comment without requesting revisions to specific sections. 
- [ ] 5. The Send Request button will be disabled by default, and only enable when an enabled section is checked off.

![image](https://user-images.githubusercontent.com/18424138/120378245-2b551a00-c2ec-11eb-8a9f-5e9d9e0b6e22.png)

**Comment by rosibaj** [comment]
should use the same modal infrastructure as @caravinci - one modal to rule them alll!!!!

**Comment by samrichca** [comment]
minimum 10 characters, no max

**Comment by rosibaj** [comment]
Tested June 17, 2021: 
- [ ]  It would be nice if i could check the box to activate, but `also` be able to activate the checkbox just by clicking in the text area and typing. Can the checkbox be enabled if you just start typing in the text box?
- [ ] Can the error only appear after i leave the box, if i have < 10, rather than right away?

**Comment by kcullion** [comment]
Tested June 18
- [ ] can you make the padding below each text area equal to the top padding. Then maybe I wouldn't need a scrollbar by default on my laptop (it only scrolls like a tiny bit)
![image](https://user-images.githubusercontent.com/18424138/122568265-93f40480-d017-11eb-8b02-9266b8ab339c.png)

**Comment by rosibaj** [comment]
@samrichca, @kcullion and i are done with feedback on this ticket.  I will move back to `in progress` to see these small changes please!

**Comment by kcullion** [comment]
@samrichca this looks great to me!!

**Comment by rosibaj** [comment]
looks amazing thank you @samrichca !
