### ISSUE TITLE
Paused status text shows incorrect date on Dashboard card

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#630]
The date showing on a PAUSED application dashboard card currently comes from the `attestationByUtc`, which is a calculated value. The value should come from the pause update event.

This will require adding the `updates` array value to the ApplicationSummary response.

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
