### ISSUE TITLE
[UI] PDF Application UI with/without watermark

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#64]
## Goal
To build the UI for the pdf with a version that adds a watermark "DRAFT" on top
- pdf always exports CURRENT state. if in form, in pdf
- Has draft watermark if in draft state, otherwise no watermark
(could be overlap with: https://github.com/icgc-argo/dac-ui/issues/60)

## Page designs for UI

- [x] **Title page**: https://zpl.io/aXjMBDp
- [x] Introduction/Application Terms (we are still considering the title here - should just pull in from the form): https://zpl.io/VOLDM7Q
- [ ] Section A: https://zpl.io/bPBmOjM
- [ ] Section B: https://zpl.io/VOLDMwX
- [ ] Section C With no collaborators: https://zpl.io/V0r0l4w
- [ ] Section C with collaborators: https://zpl.io/bAxE9rO
- [ ] Section D with content Page 1: https://zpl.io/VK7lwO7
- [ ] Section D with content Page 2: https://zpl.io/2ZwzY3X
- [ ] Section D without content example page 1 (note: the empty text boxes can be the same size as when there is content so that the applicant can write on the paper when printing the draft): https://zpl.io/blOP4o5
- [ ] Section E option 1 checked: https://zpl.io/29Gyg9z
- [ ] Section E option 2 checked: https://zpl.io/bPBmOzA
- [ ] Section F page 1: https://zpl.io/2jqwEeO
- [ ] Section F page 2: https://zpl.io/VOLDjXX
- [ ] Section G page 1: https://zpl.io/VOLDjoX
- [ ] Section G page 2: https://zpl.io/brAEgk5
- [ ] Section H: https://zpl.io/anB90mY
- [ ] **Signature page** (note - the title and instructions for this page are slightly different than the online application as it is  geared toward the printed copy: https://zpl.io/agmvllD

## Expected Outcomes
- [x] a watermark is displayed over the pdf for when it is in `DRAFT` state
- [x] button label is "Draft PDF" (should this be done here?)
- [x] the Button label changes based on application state: See “Application Form Download PDF button” specs table here: https://wiki.oicr.on.ca/display/icgcargotech/DACO+Technical+Specifications 
(Should those last two items be done elsewhere?)

**Comment by rosibaj** [comment]
keep this ticket for testing

**Comment by rosibaj** [comment]
Closing this ticket as these tasks are all completed.
