### ISSUE TITLE
Force User to Enter Special Code or Relevant Text Before Closing an Application

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/dac-ui#665]
Add logic to force users to enter a special code or text relevant to the application before allowing them to close an application.

Although not in the original MVP scope of DACO, two times users have already done this by accident.

It is quite common in many websites and we applications to use this approach.  For example, GitHub doesn't allow you to delete a repo until you re-enter the repo's full name.

We have flexibility in implementation here as there is no hard requirement as to the method, however we should look at works well for other online applications.

Further implementation details to be primed by the developer assigned to this, that info can be added her to the ticket also.

**Comment by b-f-chan** [comment]
Confirmed this feature is in QA and works correctly, moving to Ready for Staging

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
