### ISSUE TITLE
PAUSED and EXPIRED applications should download the full app package

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-ui#676]
When an application is in `PAUSED` or `EXPIRED` state, the PDF download button will only download a PDF in the front end, as in `DRAFT` state (whether there is an approved PDF uploaded or not). This download should provide the app package zip as it does in `APPROVED` state.

API ticket: https://github.com/icgc-argo/dac-api/issues/412

**Comment by b-f-chan** [comment]
Test for expired also

**Comment by b-f-chan** [comment]
Tested successfully with PAUSED app in QA, just need to test with Expired also

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
