### ISSUE TITLE
Dates in May Incorrectly Add a Period Character (".") to the Month

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/dac-ui#689]
For dates in the month of May show incorrectly in the UI with a period character (`.`) at the end of the string.

This problem only occurs May because it is the only month  with exactly 3 characters.  For all other months, the period is correct since it is an abbreviation.

This occurs in all areas:

- Dashboard card
- Banners
- Application content

For example:

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/f6f5b665-d037-41e3-bf62-9a697671bc4d)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/fac6ab09-59bc-4ff7-99a9-452cb855c77e)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/aa923740-b3e4-4adc-bf45-7841474395b0)

**Comment by b-f-chan** [comment]
Low priority, but we will try to fix for Release 4

**Comment by b-f-chan** [comment]
Confirmed corrected in QA, moving to Ready for Staging

**Comment by b-f-chan** [comment]
The `0x` format for days in single digits is fine

**Comment by anncatton** [comment]
Verified in production by @anncatton
