### ISSUE TITLE
[Data Hookup]: DACO Admin Table: Data Hookup

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#9]
**Goal:** Using the endpoint from: https://github.com/icgc-argo/dac-api/issues/1

Hook up the data in this table:  https://github.com/icgc-argo/dac-ui/issues/8

Here is the specific endpoint that we have for this available data: https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/get_applications_ 
- For data fetching, use axios. Build the first FE client to fetch data - an abstraction to pass authentication and  the endpoints 

## Expected Outcome
- [ ] The table fetches all applications and displays the correct data as per the spec 
- [ ] (Copied over from UI ticket): Default table sort: descending alpha order by status
![image](https://user-images.githubusercontent.com/18424138/120696391-8288f500-c47a-11eb-9518-88d569769fb8.png)

**Comment by rosibaj** [comment]
- talk with ann this may not be possible if auth is required as we don't have this yet 
- popping into planning for discussion on work

**Comment by kcullion** [comment]
@samrichca looking good. Some feedback:

- [ ] Filter out the DRAFT state - DACO admin wouldn't need to see the applications in that state. 
- [ ] Add same padding/margin below the table as there is above the table
![image](https://user-images.githubusercontent.com/18424138/122236322-6af33880-ce8c-11eb-905a-3b7edf6442bf.png)

**Comment by kcullion** [comment]
@samrichca added feedback to a new ticket: https://github.com/icgc-argo/dac-api/issues/34

**Comment by rosibaj** [comment]
lgtm for now - feedback in above ticket. thank you @samrichca !
