### ISSUE TITLE
[UI] UI Kit enhancements for Country select

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#93]
## Country dropdown bugs
- this should behave like a type ahead dropdown of options, like the HCMI form example below
- when filling out the country dropdown, I select a country but can't erase that to choose another country. I can type beside it to search the other countries, but this seems buggy and more like a multi-select (which was needed in other platform forms, but doesn't behave well here)
- Here is a link showing a better experience when inputting just one value: https://drive.google.com/file/d/14S5tn_22g1t3LMKwypilzv0CGGJj6-A-/view

## Other points (that could be fixed by changing the behaviour as outlined above)

- [x] For country - I shouldn't be able to add a new value in, I should have to select from the options that are listed. Like I was able to do this:
![image](https://user-images.githubusercontent.com/18424138/120553742-dcc87e00-c3c6-11eb-9b15-92e9ba8c7978.png)

- [x] when you choose a country, you can't click on the label to open the dropdown again. The user should be able to click anywhere in this field to open the dropdown
![image](https://user-images.githubusercontent.com/18424138/127537108-8bebb67b-7ab5-452f-97d0-179040b884e2.png)

- [x] For country, when I do select a value from the list of options, I can still type after that option
![image](https://user-images.githubusercontent.com/18424138/120554272-8740a100-c3c7-11eb-9d2a-0eddced45cd4.png)

- [x] The styles look different for that country field - different font sizes and no left padding. The field itself looks taller than the others as well
![image](https://user-images.githubusercontent.com/18424138/120553978-2a44eb00-c3c7-11eb-9769-032dd5a0037a.png)

- [x] Please apply these fixes to section A and B:

**Comment by caravinci** [comment]
Scope extension: restores country validation
![image](https://user-images.githubusercontent.com/2107110/128955983-e7bbf85b-88c5-48b7-93a7-1f6fb8913b04.png)

**Comment by kcullion** [comment]
as discussed with @caravinci ..this ticket covers some improvements to the UI kit single selection when there's time for this. For now, the component on the Join form is still functional. 
https://github.com/icgc-argo/platform-ui/issues/2020

**Comment by caravinci** [comment]
Thanks @kcullion! 
Did some quick preliminary analysis on the source of that newly discovered issue, and made a comment to assist fixing whenever possible.
https://github.com/icgc-argo/platform-ui/issues/2020#issuecomment-896941637

**Comment by kcullion** [comment]
tested on QA Aug 11 and looks good! just opened a small bug ticket that's not releated to the ui kit piece. thanks @caravinci 
https://github.com/icgc-argo/dac-ui/issues/361

**Comment by kcullion** [comment]
Aug 16: working in staging
@rosibaj can you test this country component and see what you think?

**Comment by rosibaj** [comment]
working much better! lgtm!

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
