### ISSUE TITLE
[UI] Applicant Dashboard feedback

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#95]
- [x] Please use the same grid system that @samrichca implemented from ARGO, that should put the dashboard cards in the same max-width container.
- [x] move the cards up a bit 
- [x] fix padding inside the card so it's consistent for the title and the content within
- [x] Capitalize card titles as per design: https://zpl.io/2ZMEE7J
- [x] make small access card a bit wider as per screenshot below

![image](https://user-images.githubusercontent.com/18424138/120658121-265eaa80-c453-11eb-91f1-845ba95784b0.png)

![image](https://user-images.githubusercontent.com/18424138/120659464-63776c80-c454-11eb-9d8a-a55636f48a51.png)

**Comment by kcullion** [comment]
thanks @ciaranschutte 
Can you just make this "Start a New Application"? 
![image](https://user-images.githubusercontent.com/18424138/122106056-72acd180-cde7-11eb-98f7-813a4be9c451.png)

Is the padding consistent inside the body area of the cards? When I make the screen a bit smaller I see this
![image](https://user-images.githubusercontent.com/18424138/122106294-bbfd2100-cde7-11eb-9cca-a7da2191e9fb.png)

I think only the title should be h1 tags. The card titles are more subheadings of the main heading
![image](https://user-images.githubusercontent.com/18424138/122106467-f4046400-cde7-11eb-9a45-e05f8a61cfe4.png)

**Comment by kcullion** [comment]
@ciaranschutte @rosibaj this one looks good to me!

**Comment by rosibaj** [comment]
changed looking good - thank you @ciaranschutte!
