### ISSUE TITLE
[Data Hookup] 2- Request Revisions Applicant Changes

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#96]
- [x] 1. When the applicant interacts with a form element in this section, and enters a new valid value into one of the fields - mark this section with a green pencil (we can't know if they do this correctly) https://zpl.io/Vqzx6DZ
**This is ready in the API - the front end just needs to show a green pencil when in `REVISIONS_MADE` state**  (right now it shows green checkmark) 

- [x] 2. The sign and submit section should have **previous pdfs deleted** and **disabled until all revised sections have green pencils**. 
This is an example that shows the sign and submit section is not disabled: https://dac.qa.argo.cancercollaboratory.org/applications/DACO-55?section=terms

![image](https://user-images.githubusercontent.com/18424138/122086573-d3c9aa80-cdd1-11eb-8671-68fb5d4b4b98.png)

### FOR TESTING PURPOSES: Application state after revised in a valid way 
Zeplin: https://zpl.io/bzdMYBG
- [x] 3 Once all sections have been revised in some way, transition the application from `REVISIONS REQUIRED` to `SIGN AND SUBMIT` 
- [x] 4. Enable this sign and submit section for resubmission of a new pdf

![image](https://user-images.githubusercontent.com/18424138/122086903-2a36e900-cdd2-11eb-9b60-b777d40e198d.png)

**Comment by kcullion** [comment]
looks good @samrichca tested on Jul 28

I now see sign and submit disabled (when I made a comment to revise that section)
![image](https://user-images.githubusercontent.com/18424138/127368100-82371802-b689-4482-ad70-078478db041d.png)

I also see the green pencils now, and the sign and submit section enables once all sections have green pencils 
![image](https://user-images.githubusercontent.com/18424138/127368858-9809b66e-66bb-4045-9a78-474d94b7543e.png)
